#!/usr/bin/env r
#
# Generate src/stubs.c from src/RcppExports.cpp function declarations.
# Run after Rcpp::compileAttributes() whenever entry points change.
#
# Usage: r -e 'source("tools/gen_stubs.R")'

pkg_name <- read.dcf("DESCRIPTION", "Package")[[1]]
exports_file <- "src/RcppExports.cpp"
stubs_file <- "src/stubs.c"

lines <- readLines(exports_file)

# Extract function declarations: RcppExport SEXP _tinytorch_funcname(args) {
prefix <- paste0("_", pkg_name, "_")
decl_pattern <- paste0("^RcppExport SEXP (", prefix, "[A-Za-z0-9_]+)\\((.*)\\)\\s*\\{")
decl_lines <- grep(decl_pattern, lines, value = TRUE)

entries <- data.frame(
  name = sub(decl_pattern, "\\1", decl_lines),
  args_str = sub(decl_pattern, "\\2", decl_lines),
  stringsAsFactors = FALSE
)

# Count args by counting SEXP parameters
entries$nargs <- vapply(entries$args_str, function(s) {
  if (nchar(trimws(s)) == 0) return(0L)
  length(strsplit(s, ",")[[1]])
}, 0L)

cat("Parsed", nrow(entries), "entry points from", exports_file, "\n")

ping_wrapper <- paste0(prefix, "C_rtorch_ping")

# Generate stubs
out <- character()
out <- c(out,
  "/* Auto-generated by tools/gen_stubs.R -- do not edit by hand */",
  "",
  "#include <R.h>",
  "#include <Rinternals.h>",
  "#include <R_ext/Rdynload.h>",
  "",
  "/* ---- Stub ping: returns 0 (backend not available) ---- */",
  "",
  "SEXP C_rtorch_ping(void) {",
  "    return ScalarInteger(0);",
  "}",
  "",
  sprintf("/* Rcpp-style wrapper for ping (matches %s) */", ping_wrapper),
  sprintf("SEXP %s(void) {", ping_wrapper),
  "    return C_rtorch_ping();",
  "}",
  "",
  "/* ---- Stub entry points ---- */",
  "",
  "static SEXP stub_error(void) {",
  sprintf('    Rf_error("%s backend not available (libtorch not found or unsupported platform)");', pkg_name),
  "    return R_NilValue;",
  "}",
  ""
)

# Generate stub functions (skip ping wrapper)
for (i in seq_len(nrow(entries))) {
  nm <- entries$name[i]
  na <- entries$nargs[i]
  if (nm == ping_wrapper) next

  args <- if (na == 0L) {
    "void"
  } else {
    paste(sprintf("SEXP a%d", seq_len(na)), collapse = ", ")
  }

  out <- c(out, sprintf("SEXP %s(%s) {", nm, args))
  if (na > 0L) {
    for (j in seq_len(na)) {
      out <- c(out, sprintf("    (void)a%d;", j))
    }
  }
  out <- c(out, "    return stub_error();", "}", "")
}

# Generate registration table
out <- c(out,
  "/* ---- Registration table ---- */",
  "",
  "static const R_CallMethodDef CallEntries[] = {"
)

for (i in seq_len(nrow(entries))) {
  out <- c(out, sprintf('    {"%s", (DL_FUNC) &%s, %d},',
                         entries$name[i], entries$name[i], entries$nargs[i]))
}

init_fn <- paste0("R_init_", pkg_name)
out <- c(out,
  "    {NULL, NULL, 0}",
  "};",
  "",
  sprintf("void %s(DllInfo *dll) {", init_fn),
  "    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);",
  "    R_useDynamicSymbols(dll, FALSE);",
  "}",
  ""
)

writeLines(out, stubs_file)
cat("Generated", stubs_file, "with", nrow(entries), "entry points\n")
