#!/usr/bin/env r
#
# Generate src/stubs.c from src/RcppExports.cpp registration table.
# Run after Rcpp::compileAttributes() whenever entry points change.
#
# Usage: r -e 'source("tools/gen_stubs.R")'

exports_file <- "src/RcppExports.cpp"
stubs_file <- "src/stubs.c"

lines <- readLines(exports_file)

# Extract registration entries: {"_Rtorch_funcname", (DL_FUNC) &_Rtorch_funcname, N},
reg_pattern <- '^\\s*\\{"(_Rtorch_[^"]+)",\\s*\\(DL_FUNC\\)\\s*&[^,]+,\\s*(\\d+)\\}.*$'
reg_lines <- grep(reg_pattern, lines, value = TRUE)

entries <- data.frame(
  name = sub(reg_pattern, "\\1", reg_lines),
  nargs = as.integer(sub(reg_pattern, "\\2", reg_lines)),
  stringsAsFactors = FALSE
)

# Ensure _Rtorch_C_rtorch_ping is in the table (the Rcpp wrapper name)
# The unprefixed C_rtorch_ping is NOT registered — only the _Rtorch_ variant
# is used by R's .Call()

cat("Parsed", nrow(entries), "entry points from", exports_file, "\n")

# Generate stubs
out <- character()
out <- c(out,
  "/* Auto-generated by tools/gen_stubs.R -- do not edit by hand */",
  "",
  "#include <R.h>",
  "#include <Rinternals.h>",
  "#include <R_ext/Rdynload.h>",
  "",
  "/* ---- Stub ping: returns 0 (backend not available) ---- */",
  "",
  "SEXP C_rtorch_ping(void) {",
  "    return ScalarInteger(0);",
  "}",
  "",
  "/* Rcpp-style wrapper for ping (same as real backend) */",
  "SEXP _Rtorch_C_rtorch_ping(void) {",
  "    return C_rtorch_ping();",
  "}",
  "",
  "/* ---- Stub entry points ---- */",
  "",
  "static SEXP rtorch_stub_error(void) {",
  '    Rf_error("Rtorch backend not available (libtorch not found or unsupported platform)");',
  "    return R_NilValue;",
  "}",
  ""
)

# Generate stub functions (skip C_rtorch_ping and its Rcpp wrapper)
ping_names <- c("C_rtorch_ping", "_Rtorch_C_rtorch_ping")
for (i in seq_len(nrow(entries))) {
  nm <- entries$name[i]
  na <- entries$nargs[i]
  if (nm %in% ping_names) next

  args <- if (na == 0L) {
    "void"
  } else {
    paste(sprintf("SEXP a%d", seq_len(na)), collapse = ", ")
  }

  # Suppress unused parameter warnings
  out <- c(out, sprintf("SEXP %s(%s) {", nm, args))
  if (na > 0L) {
    for (j in seq_len(na)) {
      out <- c(out, sprintf("    (void)a%d;", j))
    }
  }
  out <- c(out, "    return rtorch_stub_error();", "}", "")
}

# Generate registration table
out <- c(out,
  "/* ---- Registration table ---- */",
  "",
  "static const R_CallMethodDef CallEntries[] = {"
)

for (i in seq_len(nrow(entries))) {
  nm <- entries$name[i]
  # Skip bare C_rtorch_ping — only register the _Rtorch_ prefixed wrapper
  if (nm == "C_rtorch_ping") next
  out <- c(out, sprintf('    {"%s", (DL_FUNC) &%s, %d},', nm, nm, entries$nargs[i]))
}

out <- c(out,
  "    {NULL, NULL, 0}",
  "};",
  "",
  "void R_init_Rtorch(DllInfo *dll) {",
  "    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);",
  "    R_useDynamicSymbols(dll, FALSE);",
  "}",
  ""
)

writeLines(out, stubs_file)
cat("Generated", stubs_file, "with", nrow(entries), "entry points\n")
