// Auto-generated by tools/codegen.R — DO NOT EDIT
// Source: native_functions.yaml
#include "Rtorch.h"


// [[Rcpp::export]]
at::Tensor C_torch_absolute(at::Tensor self) { return at::absolute(self); }

// [[Rcpp::export]]
at::Tensor C_torch_angle(at::Tensor self) { return at::angle(self); }

// [[Rcpp::export]]
at::Tensor C_torch_view_as_complex(at::Tensor self) { return at::view_as_complex(self); }

// [[Rcpp::export]]
at::Tensor C_torch_sgn(at::Tensor self) { return at::sgn(self); }

// [[Rcpp::export]]
at::Tensor C_torch_acos(at::Tensor self) { return at::acos(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arccos(at::Tensor self) { return at::arccos(self); }

// [[Rcpp::export]]
at::Tensor C_torch_all(at::Tensor self, int64_t dim, bool keepdim) { return at::all(self, dim, keepdim); }

// [[Rcpp::export]]
at::Tensor C_torch_any(at::Tensor self, int64_t dim, bool keepdim) { return at::any(self, dim, keepdim); }

// [[Rcpp::export]]
at::Tensor C_torch_acosh(at::Tensor self) { return at::acosh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arccosh(at::Tensor self) { return at::arccosh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_asinh(at::Tensor self) { return at::asinh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arcsinh(at::Tensor self) { return at::arcsinh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_atanh(at::Tensor self) { return at::atanh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arctanh(at::Tensor self) { return at::arctanh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_asin(at::Tensor self) { return at::asin(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arcsin(at::Tensor self) { return at::arcsin(self); }

// [[Rcpp::export]]
at::Tensor C_torch_atan(at::Tensor self) { return at::atan(self); }

// [[Rcpp::export]]
at::Tensor C_torch_arctan(at::Tensor self) { return at::arctan(self); }

// [[Rcpp::export]]
at::Tensor C_torch_atleast_1d(at::Tensor self) { return at::atleast_1d(self); }

// [[Rcpp::export]]
at::Tensor C_torch_atleast_2d(at::Tensor self) { return at::atleast_2d(self); }

// [[Rcpp::export]]
at::Tensor C_torch_atleast_3d(at::Tensor self) { return at::atleast_3d(self); }

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_not(at::Tensor self) { return at::bitwise_not(self); }

// [[Rcpp::export]]
at::Tensor C_torch_copysign(at::Tensor self, at::Tensor other) { return at::copysign(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_logical_xor(at::Tensor self, at::Tensor other) { return at::logical_xor(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_logical_and(at::Tensor self, at::Tensor other) { return at::logical_and(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_logical_or(at::Tensor self, at::Tensor other) { return at::logical_or(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_clamp_max(at::Tensor self, SEXP other) {
    return at::clamp_max(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_clamp_min(at::Tensor self, SEXP other) {
    return at::clamp_min(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_cosh(at::Tensor self) { return at::cosh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_corrcoef(at::Tensor self) { return at::corrcoef(self); }

// [[Rcpp::export]]
at::Tensor C_torch_diag_embed(at::Tensor self, int64_t offset, int64_t dim1, int64_t dim2) { return at::diag_embed(self, offset, dim1, dim2); }

// [[Rcpp::export]]
at::Tensor C_torch_diagflat(at::Tensor self, int64_t offset) { return at::diagflat(self, offset); }

// [[Rcpp::export]]
at::Tensor C_torch_diagonal(at::Tensor self, int64_t offset, int64_t dim1, int64_t dim2) { return at::diagonal(self, offset, dim1, dim2); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_diagonal(at::Tensor self, int64_t offset, int64_t dim1, int64_t dim2) { return at::linalg_diagonal(self, offset, dim1, dim2); }

// [[Rcpp::export]]
at::Tensor C_torch_divide(at::Tensor self, at::Tensor other) { return at::divide(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_true_divide(at::Tensor self, at::Tensor other) { return at::true_divide(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_dot(at::Tensor self, at::Tensor tensor) { return at::dot(self, tensor); }

// [[Rcpp::export]]
at::Tensor C_torch_vdot(at::Tensor self, at::Tensor other) { return at::vdot(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_erf(at::Tensor self) { return at::erf(self); }

// [[Rcpp::export]]
at::Tensor C_torch_erfc(at::Tensor self) { return at::erfc(self); }

// [[Rcpp::export]]
at::Tensor C_torch_exp2(at::Tensor self) { return at::exp2(self); }

// [[Rcpp::export]]
at::Tensor C_torch_expm1(at::Tensor self) { return at::expm1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_fill(at::Tensor self, SEXP other) {
    return at::fill(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_frac(at::Tensor self) { return at::frac(self); }

// [[Rcpp::export]]
at::Tensor C_torch_gcd(at::Tensor self, at::Tensor other) { return at::gcd(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_lcm(at::Tensor self, at::Tensor other) { return at::lcm(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_isnan(at::Tensor self) { return at::isnan(self); }

// [[Rcpp::export]]
at::Tensor C_torch_isreal(at::Tensor self) { return at::isreal(self); }

// [[Rcpp::export]]
at::Tensor C_torch_kron(at::Tensor self, at::Tensor other) { return at::kron(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_log1p(at::Tensor self) { return at::log1p(self); }

// [[Rcpp::export]]
at::Tensor C_torch_logaddexp(at::Tensor self, at::Tensor other) { return at::logaddexp(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_logaddexp2(at::Tensor self, at::Tensor other) { return at::logaddexp2(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_xlogy(at::Tensor self, at::Tensor other) { return at::xlogy(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_logcumsumexp(at::Tensor self, int64_t dim) { return at::logcumsumexp(self, dim); }

// [[Rcpp::export]]
at::Tensor C_torch_matrix_power(at::Tensor self, int64_t n) { return at::matrix_power(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_matrix_exp(at::Tensor self) { return at::matrix_exp(self); }

// [[Rcpp::export]]
at::Tensor C_torch_median(at::Tensor self) { return at::median(self); }

// [[Rcpp::export]]
at::Tensor C_torch_nanmedian(at::Tensor self) { return at::nanmedian(self); }

// [[Rcpp::export]]
at::Tensor C_torch_multiply(at::Tensor self, at::Tensor other) { return at::multiply(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_mv(at::Tensor self, at::Tensor vec) { return at::mv(self, vec); }

// [[Rcpp::export]]
at::Tensor C_torch_mvlgamma(at::Tensor self, int64_t p) { return at::mvlgamma(self, p); }

// [[Rcpp::export]]
at::Tensor C_torch_pdist(at::Tensor self, double p) { return at::pdist(self, p); }

// [[Rcpp::export]]
at::Tensor C_torch_movedim(at::Tensor self, int64_t source, int64_t destination) { return at::movedim(self, source, destination); }

// [[Rcpp::export]]
at::Tensor C_torch_moveaxis(at::Tensor self, int64_t source, int64_t destination) { return at::moveaxis(self, source, destination); }

// [[Rcpp::export]]
at::Tensor C_torch_adjoint(at::Tensor self) { return at::adjoint(self); }

// [[Rcpp::export]]
at::Tensor C_torch_pixel_shuffle(at::Tensor self, int64_t upscale_factor) { return at::pixel_shuffle(self, upscale_factor); }

// [[Rcpp::export]]
at::Tensor C_torch_pixel_unshuffle(at::Tensor self, int64_t downscale_factor) { return at::pixel_unshuffle(self, downscale_factor); }

// [[Rcpp::export]]
at::Tensor C_torch_pinverse(at::Tensor self, double rcond) { return at::pinverse(self, rcond); }

// [[Rcpp::export]]
at::Tensor C_torch_rad2deg(at::Tensor self) { return at::rad2deg(self); }

// [[Rcpp::export]]
at::Tensor C_torch_deg2rad(at::Tensor self) { return at::deg2rad(self); }

// [[Rcpp::export]]
at::Tensor C_torch_ravel(at::Tensor self) { return at::ravel(self); }

// [[Rcpp::export]]
at::Tensor C_torch_reciprocal(at::Tensor self) { return at::reciprocal(self); }

// [[Rcpp::export]]
at::Tensor C_torch_negative(at::Tensor self) { return at::negative(self); }

// [[Rcpp::export]]
at::Tensor C_torch_relu6(at::Tensor self) { return at::relu6(self); }

// [[Rcpp::export]]
at::Tensor C_torch_prelu(at::Tensor self, at::Tensor weight) { return at::prelu(self, weight); }

// [[Rcpp::export]]
at::Tensor C_torch_hardshrink(at::Tensor self, SEXP other) {
    return at::hardshrink(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_selu(at::Tensor self) { return at::selu(self); }

// [[Rcpp::export]]
at::Tensor C_torch_celu(at::Tensor self, SEXP other) {
    return at::celu(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_silu(at::Tensor self) { return at::silu(self); }

// [[Rcpp::export]]
at::Tensor C_torch_mish(at::Tensor self) { return at::mish(self); }

// [[Rcpp::export]]
at::Tensor C_torch_sinc(at::Tensor self) { return at::sinc(self); }

// [[Rcpp::export]]
at::Tensor C_torch_sinh(at::Tensor self) { return at::sinh(self); }

// [[Rcpp::export]]
at::Tensor C_torch_square(at::Tensor self) { return at::square(self); }

// [[Rcpp::export]]
at::Tensor C_torch_tan(at::Tensor self) { return at::tan(self); }

// [[Rcpp::export]]
at::Tensor C_torch_fliplr(at::Tensor self) { return at::fliplr(self); }

// [[Rcpp::export]]
at::Tensor C_torch_flipud(at::Tensor self) { return at::flipud(self); }

// [[Rcpp::export]]
at::Tensor C_torch_fix(at::Tensor self) { return at::fix(self); }

// [[Rcpp::export]]
at::Tensor C_torch_var(at::Tensor self, bool unbiased) { return at::var(self, unbiased); }

// [[Rcpp::export]]
at::Tensor C_torch_positive(at::Tensor self) { return at::positive(self); }

// [[Rcpp::export]]
at::Tensor C_torch_subtract(at::Tensor self, at::Tensor other, SEXP alpha_sexp) {
    return at::subtract(self, other, sexp_to_scalar(alpha_sexp));
}

// [[Rcpp::export]]
at::Tensor C_torch_rsub(at::Tensor self, at::Tensor other, SEXP alpha_sexp) {
    return at::rsub(self, other, sexp_to_scalar(alpha_sexp));
}

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_and(at::Tensor self, SEXP other) {
    return at::bitwise_and(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_or(at::Tensor self, SEXP other) {
    return at::bitwise_or(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_xor(at::Tensor self, SEXP other) {
    return at::bitwise_xor(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_left_shift(at::Tensor self, at::Tensor other) { return at::bitwise_left_shift(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_bitwise_right_shift(at::Tensor self, at::Tensor other) { return at::bitwise_right_shift(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_diag(at::Tensor self, int64_t diagonal) { return at::diag(self, diagonal); }

// [[Rcpp::export]]
at::Tensor C_torch_tril(at::Tensor self, int64_t diagonal) { return at::tril(self, diagonal); }

// [[Rcpp::export]]
at::Tensor C_torch_trace(at::Tensor self) { return at::trace(self); }

// [[Rcpp::export]]
at::Tensor C_torch_not_equal(at::Tensor self, SEXP other) {
    return at::not_equal(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_greater_equal(at::Tensor self, SEXP other) {
    return at::greater_equal(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_less_equal(at::Tensor self, SEXP other) {
    return at::less_equal(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_greater(at::Tensor self, SEXP other) {
    return at::greater(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_less(at::Tensor self, SEXP other) {
    return at::less(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_take(at::Tensor self, at::Tensor index) { return at::take(self, index); }

// [[Rcpp::export]]
at::Tensor C_torch_masked_select(at::Tensor self, at::Tensor mask) { return at::masked_select(self, mask); }

// [[Rcpp::export]]
at::Tensor C_torch_nonzero(at::Tensor self) { return at::nonzero(self); }

// [[Rcpp::export]]
at::Tensor C_torch_argwhere(at::Tensor self) { return at::argwhere(self); }

// [[Rcpp::export]]
at::Tensor C_torch_swapaxes(at::Tensor self, int64_t axis0, int64_t axis1) { return at::swapaxes(self, axis0, axis1); }

// [[Rcpp::export]]
at::Tensor C_torch_swapdims(at::Tensor self, int64_t dim0, int64_t dim1) { return at::swapdims(self, dim0, dim1); }

// [[Rcpp::export]]
at::Tensor C_torch_cholesky(at::Tensor self, bool upper) { return at::cholesky(self, upper); }

// [[Rcpp::export]]
at::Tensor C_torch_cholesky_inverse(at::Tensor self, bool upper) { return at::cholesky_inverse(self, upper); }

// [[Rcpp::export]]
at::Tensor C_torch_orgqr(at::Tensor self, at::Tensor input2) { return at::orgqr(self, input2); }

// [[Rcpp::export]]
at::Tensor C_torch_lgamma(at::Tensor self) { return at::lgamma(self); }

// [[Rcpp::export]]
at::Tensor C_torch_digamma(at::Tensor self) { return at::digamma(self); }

// [[Rcpp::export]]
at::Tensor C_torch_erfinv(at::Tensor self) { return at::erfinv(self); }

// [[Rcpp::export]]
at::Tensor C_torch_i0(at::Tensor self) { return at::i0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_signbit(at::Tensor self) { return at::signbit(self); }

// [[Rcpp::export]]
at::Tensor C_torch_dist(at::Tensor self, at::Tensor other, SEXP p_sexp) {
    return at::dist(self, other, sexp_to_scalar(p_sexp));
}

// [[Rcpp::export]]
at::Tensor C_torch_atan2(at::Tensor self, at::Tensor other) { return at::atan2(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_arctan2(at::Tensor self, at::Tensor other) { return at::arctan2(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_lerp(at::Tensor self, at::Tensor end, SEXP weight_sexp) {
    return at::lerp(self, end, sexp_to_scalar(weight_sexp));
}

// [[Rcpp::export]]
at::Tensor C_torch_fmod(at::Tensor self, SEXP other) {
    return at::fmod(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_hypot(at::Tensor self, at::Tensor other) { return at::hypot(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_igamma(at::Tensor self, at::Tensor other) { return at::igamma(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_igammac(at::Tensor self, at::Tensor other) { return at::igammac(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_nextafter(at::Tensor self, at::Tensor other) { return at::nextafter(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_fmin(at::Tensor self, at::Tensor other) { return at::fmin(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_fmax(at::Tensor self, at::Tensor other) { return at::fmax(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_minimum(at::Tensor self, at::Tensor other) { return at::minimum(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_msort(at::Tensor self) { return at::msort(self); }

// [[Rcpp::export]]
at::Tensor C_torch_argsort(at::Tensor self, int64_t dim, bool descending) { return at::argsort(self, dim, descending); }

// [[Rcpp::export]]
at::Tensor C_torch_float_power(at::Tensor self, at::Tensor exponent) { return at::float_power(self, exponent); }

// [[Rcpp::export]]
at::Tensor C_torch_alias(at::Tensor self) { return at::alias(self); }

// [[Rcpp::export]]
at::Tensor C_torch_glu(at::Tensor self, int64_t dim) { return at::glu(self, dim); }

// [[Rcpp::export]]
at::Tensor C_torch_hardsigmoid(at::Tensor self) { return at::hardsigmoid(self); }

// [[Rcpp::export]]
at::Tensor C_torch_hardswish(at::Tensor self) { return at::hardswish(self); }

// [[Rcpp::export]]
at::Tensor C_torch_leaky_relu(at::Tensor self, SEXP other) {
    return at::leaky_relu(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_log_sigmoid(at::Tensor self) { return at::log_sigmoid(self); }

// [[Rcpp::export]]
at::Tensor C_torch_softshrink(at::Tensor self, SEXP other) {
    return at::softshrink(self, sexp_to_scalar(other));
}

// [[Rcpp::export]]
at::Tensor C_torch_isfinite(at::Tensor self) { return at::isfinite(self); }

// [[Rcpp::export]]
at::Tensor C_torch_isinf(at::Tensor self) { return at::isinf(self); }

// [[Rcpp::export]]
at::Tensor C_torch_isposinf(at::Tensor self) { return at::isposinf(self); }

// [[Rcpp::export]]
at::Tensor C_torch_isneginf(at::Tensor self) { return at::isneginf(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_entr(at::Tensor self) { return at::special_entr(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_ndtri(at::Tensor self) { return at::special_ndtri(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_log_ndtr(at::Tensor self) { return at::special_log_ndtr(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_expm1(at::Tensor self) { return at::special_expm1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_exp2(at::Tensor self) { return at::special_exp2(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_psi(at::Tensor self) { return at::special_psi(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_digamma(at::Tensor self) { return at::special_digamma(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_gammaln(at::Tensor self) { return at::special_gammaln(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_erf(at::Tensor self) { return at::special_erf(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_erfc(at::Tensor self) { return at::special_erfc(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_erfcx(at::Tensor self) { return at::special_erfcx(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_erfinv(at::Tensor self) { return at::special_erfinv(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_ndtr(at::Tensor self) { return at::special_ndtr(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_xlog1py(at::Tensor self, at::Tensor other) { return at::special_xlog1py(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_special_xlogy(at::Tensor self, at::Tensor other) { return at::special_xlogy(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_special_zeta(at::Tensor self, at::Tensor other) { return at::special_zeta(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_special_i0(at::Tensor self) { return at::special_i0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_i0e(at::Tensor self) { return at::special_i0e(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_i1(at::Tensor self) { return at::special_i1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_i1e(at::Tensor self) { return at::special_i1e(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_expit(at::Tensor self) { return at::special_expit(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_sinc(at::Tensor self) { return at::special_sinc(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_round(at::Tensor self, int64_t decimals) { return at::special_round(self, decimals); }

// [[Rcpp::export]]
at::Tensor C_torch_special_log1p(at::Tensor self) { return at::special_log1p(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_gammainc(at::Tensor self, at::Tensor other) { return at::special_gammainc(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_special_gammaincc(at::Tensor self, at::Tensor other) { return at::special_gammaincc(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_special_multigammaln(at::Tensor self, int64_t p) { return at::special_multigammaln(self, p); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_cholesky(at::Tensor self, bool upper) { return at::linalg_cholesky(self, upper); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_det(at::Tensor self) { return at::linalg_det(self); }

// [[Rcpp::export]]
at::Tensor C_torch_det(at::Tensor self) { return at::det(self); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_matmul(at::Tensor self, at::Tensor other) { return at::linalg_matmul(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_matrix_exp(at::Tensor self) { return at::linalg_matrix_exp(self); }

// [[Rcpp::export]]
at::Tensor C_torch_logdet(at::Tensor self) { return at::logdet(self); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_eigvals(at::Tensor self) { return at::linalg_eigvals(self); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_householder_product(at::Tensor self, at::Tensor tau) { return at::linalg_householder_product(self, tau); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_inv(at::Tensor self) { return at::linalg_inv(self); }

// [[Rcpp::export]]
at::Tensor C_torch_inverse(at::Tensor self) { return at::inverse(self); }

// [[Rcpp::export]]
at::Tensor C_torch_inner(at::Tensor self, at::Tensor other) { return at::inner(self, other); }

// [[Rcpp::export]]
at::Tensor C_torch_ger(at::Tensor self, at::Tensor vec2) { return at::ger(self, vec2); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_tensorinv(at::Tensor self, int64_t ind) { return at::linalg_tensorinv(self, ind); }

// [[Rcpp::export]]
at::Tensor C_torch_linalg_matrix_power(at::Tensor self, int64_t n) { return at::linalg_matrix_power(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_airy_ai(at::Tensor self) { return at::special_airy_ai(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_bessel_j0(at::Tensor self) { return at::special_bessel_j0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_bessel_j1(at::Tensor self) { return at::special_bessel_j1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_bessel_y0(at::Tensor self) { return at::special_bessel_y0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_bessel_y1(at::Tensor self) { return at::special_bessel_y1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_chebyshev_polynomial_t(at::Tensor self, at::Tensor n) { return at::special_chebyshev_polynomial_t(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_chebyshev_polynomial_u(at::Tensor self, at::Tensor n) { return at::special_chebyshev_polynomial_u(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_chebyshev_polynomial_v(at::Tensor self, at::Tensor n) { return at::special_chebyshev_polynomial_v(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_chebyshev_polynomial_w(at::Tensor self, at::Tensor n) { return at::special_chebyshev_polynomial_w(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_hermite_polynomial_h(at::Tensor self, at::Tensor n) { return at::special_hermite_polynomial_h(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_hermite_polynomial_he(at::Tensor self, at::Tensor n) { return at::special_hermite_polynomial_he(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_laguerre_polynomial_l(at::Tensor self, at::Tensor n) { return at::special_laguerre_polynomial_l(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_legendre_polynomial_p(at::Tensor self, at::Tensor n) { return at::special_legendre_polynomial_p(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_modified_bessel_i0(at::Tensor self) { return at::special_modified_bessel_i0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_modified_bessel_i1(at::Tensor self) { return at::special_modified_bessel_i1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_modified_bessel_k0(at::Tensor self) { return at::special_modified_bessel_k0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_modified_bessel_k1(at::Tensor self) { return at::special_modified_bessel_k1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_scaled_modified_bessel_k0(at::Tensor self) { return at::special_scaled_modified_bessel_k0(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_scaled_modified_bessel_k1(at::Tensor self) { return at::special_scaled_modified_bessel_k1(self); }

// [[Rcpp::export]]
at::Tensor C_torch_special_shifted_chebyshev_polynomial_t(at::Tensor self, at::Tensor n) { return at::special_shifted_chebyshev_polynomial_t(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_shifted_chebyshev_polynomial_u(at::Tensor self, at::Tensor n) { return at::special_shifted_chebyshev_polynomial_u(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_shifted_chebyshev_polynomial_v(at::Tensor self, at::Tensor n) { return at::special_shifted_chebyshev_polynomial_v(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_shifted_chebyshev_polynomial_w(at::Tensor self, at::Tensor n) { return at::special_shifted_chebyshev_polynomial_w(self, n); }

// [[Rcpp::export]]
at::Tensor C_torch_special_spherical_bessel_j0(at::Tensor self) { return at::special_spherical_bessel_j0(self); }
