# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_as_array <- function(self) {
    .Call(`_Rtorch_C_as_array`, self)
}

C_tensor_shape <- function(self) {
    .Call(`_Rtorch_C_tensor_shape`, self)
}

C_tensor_dtype <- function(self) {
    .Call(`_Rtorch_C_tensor_dtype`, self)
}

C_tensor_device <- function(self) {
    .Call(`_Rtorch_C_tensor_device`, self)
}

C_tensor_ndim <- function(self) {
    .Call(`_Rtorch_C_tensor_ndim`, self)
}

C_tensor_numel <- function(self) {
    .Call(`_Rtorch_C_tensor_numel`, self)
}

C_tensor_requires_grad <- function(self) {
    .Call(`_Rtorch_C_tensor_requires_grad`, self)
}

C_tensor_print <- function(self) {
    .Call(`_Rtorch_C_tensor_print`, self)
}

cpp_fused_relu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu`, input_sexp)
}

cpp_fused_relu_sigmoid <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu_sigmoid`, input_sexp)
}

cpp_fused_relu_sigmoid_tanh <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu_sigmoid_tanh`, input_sexp)
}

cpp_fused_silu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_silu`, input_sexp)
}

cpp_fused_gelu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_gelu`, input_sexp)
}

cpp_fused_sincos <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_sincos`, input_sexp)
}

cpp_fused_softcap <- function(input_sexp, cap_sexp) {
    .Call(`_Rtorch_cpp_fused_softcap`, input_sexp, cap_sexp)
}

cpp_fused_rmsnorm <- function(input_sexp, weight_sexp, eps_sexp) {
    .Call(`_Rtorch_cpp_fused_rmsnorm`, input_sexp, weight_sexp, eps_sexp)
}

cpp_tensor_shapes_key <- function(tensor_list) {
    .Call(`_Rtorch_cpp_tensor_shapes_key`, tensor_list)
}

C_torch_absolute <- function(self) {
    .Call(`_Rtorch_C_torch_absolute`, self)
}

C_torch_angle <- function(self) {
    .Call(`_Rtorch_C_torch_angle`, self)
}

C_torch_view_as_complex <- function(self) {
    .Call(`_Rtorch_C_torch_view_as_complex`, self)
}

C_torch_sgn <- function(self) {
    .Call(`_Rtorch_C_torch_sgn`, self)
}

C_torch_acos <- function(self) {
    .Call(`_Rtorch_C_torch_acos`, self)
}

C_torch_arccos <- function(self) {
    .Call(`_Rtorch_C_torch_arccos`, self)
}

C_torch_all <- function(self, dim, keepdim) {
    .Call(`_Rtorch_C_torch_all`, self, dim, keepdim)
}

C_torch_any <- function(self, dim, keepdim) {
    .Call(`_Rtorch_C_torch_any`, self, dim, keepdim)
}

C_torch_acosh <- function(self) {
    .Call(`_Rtorch_C_torch_acosh`, self)
}

C_torch_arccosh <- function(self) {
    .Call(`_Rtorch_C_torch_arccosh`, self)
}

C_torch_asinh <- function(self) {
    .Call(`_Rtorch_C_torch_asinh`, self)
}

C_torch_arcsinh <- function(self) {
    .Call(`_Rtorch_C_torch_arcsinh`, self)
}

C_torch_atanh <- function(self) {
    .Call(`_Rtorch_C_torch_atanh`, self)
}

C_torch_arctanh <- function(self) {
    .Call(`_Rtorch_C_torch_arctanh`, self)
}

C_torch_asin <- function(self) {
    .Call(`_Rtorch_C_torch_asin`, self)
}

C_torch_arcsin <- function(self) {
    .Call(`_Rtorch_C_torch_arcsin`, self)
}

C_torch_atan <- function(self) {
    .Call(`_Rtorch_C_torch_atan`, self)
}

C_torch_arctan <- function(self) {
    .Call(`_Rtorch_C_torch_arctan`, self)
}

C_torch_atleast_1d <- function(self) {
    .Call(`_Rtorch_C_torch_atleast_1d`, self)
}

C_torch_atleast_2d <- function(self) {
    .Call(`_Rtorch_C_torch_atleast_2d`, self)
}

C_torch_atleast_3d <- function(self) {
    .Call(`_Rtorch_C_torch_atleast_3d`, self)
}

C_torch_bitwise_not <- function(self) {
    .Call(`_Rtorch_C_torch_bitwise_not`, self)
}

C_torch_copysign <- function(self, other) {
    .Call(`_Rtorch_C_torch_copysign`, self, other)
}

C_torch_logical_xor <- function(self, other) {
    .Call(`_Rtorch_C_torch_logical_xor`, self, other)
}

C_torch_logical_and <- function(self, other) {
    .Call(`_Rtorch_C_torch_logical_and`, self, other)
}

C_torch_logical_or <- function(self, other) {
    .Call(`_Rtorch_C_torch_logical_or`, self, other)
}

C_torch_clamp_max <- function(self, other) {
    .Call(`_Rtorch_C_torch_clamp_max`, self, other)
}

C_torch_clamp_min <- function(self, other) {
    .Call(`_Rtorch_C_torch_clamp_min`, self, other)
}

C_torch_cosh <- function(self) {
    .Call(`_Rtorch_C_torch_cosh`, self)
}

C_torch_corrcoef <- function(self) {
    .Call(`_Rtorch_C_torch_corrcoef`, self)
}

C_torch_diag_embed <- function(self, offset, dim1, dim2) {
    .Call(`_Rtorch_C_torch_diag_embed`, self, offset, dim1, dim2)
}

C_torch_diagflat <- function(self, offset) {
    .Call(`_Rtorch_C_torch_diagflat`, self, offset)
}

C_torch_diagonal <- function(self, offset, dim1, dim2) {
    .Call(`_Rtorch_C_torch_diagonal`, self, offset, dim1, dim2)
}

C_torch_linalg_diagonal <- function(self, offset, dim1, dim2) {
    .Call(`_Rtorch_C_torch_linalg_diagonal`, self, offset, dim1, dim2)
}

C_torch_divide <- function(self, other) {
    .Call(`_Rtorch_C_torch_divide`, self, other)
}

C_torch_true_divide <- function(self, other) {
    .Call(`_Rtorch_C_torch_true_divide`, self, other)
}

C_torch_dot <- function(self, tensor) {
    .Call(`_Rtorch_C_torch_dot`, self, tensor)
}

C_torch_vdot <- function(self, other) {
    .Call(`_Rtorch_C_torch_vdot`, self, other)
}

C_torch_erf <- function(self) {
    .Call(`_Rtorch_C_torch_erf`, self)
}

C_torch_erfc <- function(self) {
    .Call(`_Rtorch_C_torch_erfc`, self)
}

C_torch_exp2 <- function(self) {
    .Call(`_Rtorch_C_torch_exp2`, self)
}

C_torch_expm1 <- function(self) {
    .Call(`_Rtorch_C_torch_expm1`, self)
}

C_torch_fill <- function(self, other) {
    .Call(`_Rtorch_C_torch_fill`, self, other)
}

C_torch_frac <- function(self) {
    .Call(`_Rtorch_C_torch_frac`, self)
}

C_torch_gcd <- function(self, other) {
    .Call(`_Rtorch_C_torch_gcd`, self, other)
}

C_torch_lcm <- function(self, other) {
    .Call(`_Rtorch_C_torch_lcm`, self, other)
}

C_torch_isnan <- function(self) {
    .Call(`_Rtorch_C_torch_isnan`, self)
}

C_torch_isreal <- function(self) {
    .Call(`_Rtorch_C_torch_isreal`, self)
}

C_torch_kron <- function(self, other) {
    .Call(`_Rtorch_C_torch_kron`, self, other)
}

C_torch_log1p <- function(self) {
    .Call(`_Rtorch_C_torch_log1p`, self)
}

C_torch_logaddexp <- function(self, other) {
    .Call(`_Rtorch_C_torch_logaddexp`, self, other)
}

C_torch_logaddexp2 <- function(self, other) {
    .Call(`_Rtorch_C_torch_logaddexp2`, self, other)
}

C_torch_xlogy <- function(self, other) {
    .Call(`_Rtorch_C_torch_xlogy`, self, other)
}

C_torch_logcumsumexp <- function(self, dim) {
    .Call(`_Rtorch_C_torch_logcumsumexp`, self, dim)
}

C_torch_matrix_power <- function(self, n) {
    .Call(`_Rtorch_C_torch_matrix_power`, self, n)
}

C_torch_matrix_exp <- function(self) {
    .Call(`_Rtorch_C_torch_matrix_exp`, self)
}

C_torch_median <- function(self) {
    .Call(`_Rtorch_C_torch_median`, self)
}

C_torch_nanmedian <- function(self) {
    .Call(`_Rtorch_C_torch_nanmedian`, self)
}

C_torch_multiply <- function(self, other) {
    .Call(`_Rtorch_C_torch_multiply`, self, other)
}

C_torch_mv <- function(self, vec) {
    .Call(`_Rtorch_C_torch_mv`, self, vec)
}

C_torch_mvlgamma <- function(self, p) {
    .Call(`_Rtorch_C_torch_mvlgamma`, self, p)
}

C_torch_pdist <- function(self, p) {
    .Call(`_Rtorch_C_torch_pdist`, self, p)
}

C_torch_movedim <- function(self, source, destination) {
    .Call(`_Rtorch_C_torch_movedim`, self, source, destination)
}

C_torch_moveaxis <- function(self, source, destination) {
    .Call(`_Rtorch_C_torch_moveaxis`, self, source, destination)
}

C_torch_adjoint <- function(self) {
    .Call(`_Rtorch_C_torch_adjoint`, self)
}

C_torch_pixel_shuffle <- function(self, upscale_factor) {
    .Call(`_Rtorch_C_torch_pixel_shuffle`, self, upscale_factor)
}

C_torch_pixel_unshuffle <- function(self, downscale_factor) {
    .Call(`_Rtorch_C_torch_pixel_unshuffle`, self, downscale_factor)
}

C_torch_pinverse <- function(self, rcond) {
    .Call(`_Rtorch_C_torch_pinverse`, self, rcond)
}

C_torch_rad2deg <- function(self) {
    .Call(`_Rtorch_C_torch_rad2deg`, self)
}

C_torch_deg2rad <- function(self) {
    .Call(`_Rtorch_C_torch_deg2rad`, self)
}

C_torch_ravel <- function(self) {
    .Call(`_Rtorch_C_torch_ravel`, self)
}

C_torch_reciprocal <- function(self) {
    .Call(`_Rtorch_C_torch_reciprocal`, self)
}

C_torch_negative <- function(self) {
    .Call(`_Rtorch_C_torch_negative`, self)
}

C_torch_relu6 <- function(self) {
    .Call(`_Rtorch_C_torch_relu6`, self)
}

C_torch_prelu <- function(self, weight) {
    .Call(`_Rtorch_C_torch_prelu`, self, weight)
}

C_torch_hardshrink <- function(self, other) {
    .Call(`_Rtorch_C_torch_hardshrink`, self, other)
}

C_torch_selu <- function(self) {
    .Call(`_Rtorch_C_torch_selu`, self)
}

C_torch_celu <- function(self, other) {
    .Call(`_Rtorch_C_torch_celu`, self, other)
}

C_torch_silu <- function(self) {
    .Call(`_Rtorch_C_torch_silu`, self)
}

C_torch_mish <- function(self) {
    .Call(`_Rtorch_C_torch_mish`, self)
}

C_torch_sinc <- function(self) {
    .Call(`_Rtorch_C_torch_sinc`, self)
}

C_torch_sinh <- function(self) {
    .Call(`_Rtorch_C_torch_sinh`, self)
}

C_torch_square <- function(self) {
    .Call(`_Rtorch_C_torch_square`, self)
}

C_torch_tan <- function(self) {
    .Call(`_Rtorch_C_torch_tan`, self)
}

C_torch_fliplr <- function(self) {
    .Call(`_Rtorch_C_torch_fliplr`, self)
}

C_torch_flipud <- function(self) {
    .Call(`_Rtorch_C_torch_flipud`, self)
}

C_torch_fix <- function(self) {
    .Call(`_Rtorch_C_torch_fix`, self)
}

C_torch_var <- function(self, unbiased) {
    .Call(`_Rtorch_C_torch_var`, self, unbiased)
}

C_torch_positive <- function(self) {
    .Call(`_Rtorch_C_torch_positive`, self)
}

C_torch_subtract <- function(self, other, alpha_sexp) {
    .Call(`_Rtorch_C_torch_subtract`, self, other, alpha_sexp)
}

C_torch_rsub <- function(self, other, alpha_sexp) {
    .Call(`_Rtorch_C_torch_rsub`, self, other, alpha_sexp)
}

C_torch_bitwise_and <- function(self, other) {
    .Call(`_Rtorch_C_torch_bitwise_and`, self, other)
}

C_torch_bitwise_or <- function(self, other) {
    .Call(`_Rtorch_C_torch_bitwise_or`, self, other)
}

C_torch_bitwise_xor <- function(self, other) {
    .Call(`_Rtorch_C_torch_bitwise_xor`, self, other)
}

C_torch_bitwise_left_shift <- function(self, other) {
    .Call(`_Rtorch_C_torch_bitwise_left_shift`, self, other)
}

C_torch_bitwise_right_shift <- function(self, other) {
    .Call(`_Rtorch_C_torch_bitwise_right_shift`, self, other)
}

C_torch_diag <- function(self, diagonal) {
    .Call(`_Rtorch_C_torch_diag`, self, diagonal)
}

C_torch_tril <- function(self, diagonal) {
    .Call(`_Rtorch_C_torch_tril`, self, diagonal)
}

C_torch_trace <- function(self) {
    .Call(`_Rtorch_C_torch_trace`, self)
}

C_torch_not_equal <- function(self, other) {
    .Call(`_Rtorch_C_torch_not_equal`, self, other)
}

C_torch_greater_equal <- function(self, other) {
    .Call(`_Rtorch_C_torch_greater_equal`, self, other)
}

C_torch_less_equal <- function(self, other) {
    .Call(`_Rtorch_C_torch_less_equal`, self, other)
}

C_torch_greater <- function(self, other) {
    .Call(`_Rtorch_C_torch_greater`, self, other)
}

C_torch_less <- function(self, other) {
    .Call(`_Rtorch_C_torch_less`, self, other)
}

C_torch_take <- function(self, index) {
    .Call(`_Rtorch_C_torch_take`, self, index)
}

C_torch_masked_select <- function(self, mask) {
    .Call(`_Rtorch_C_torch_masked_select`, self, mask)
}

C_torch_nonzero <- function(self) {
    .Call(`_Rtorch_C_torch_nonzero`, self)
}

C_torch_argwhere <- function(self) {
    .Call(`_Rtorch_C_torch_argwhere`, self)
}

C_torch_swapaxes <- function(self, axis0, axis1) {
    .Call(`_Rtorch_C_torch_swapaxes`, self, axis0, axis1)
}

C_torch_swapdims <- function(self, dim0, dim1) {
    .Call(`_Rtorch_C_torch_swapdims`, self, dim0, dim1)
}

C_torch_cholesky <- function(self, upper) {
    .Call(`_Rtorch_C_torch_cholesky`, self, upper)
}

C_torch_cholesky_inverse <- function(self, upper) {
    .Call(`_Rtorch_C_torch_cholesky_inverse`, self, upper)
}

C_torch_orgqr <- function(self, input2) {
    .Call(`_Rtorch_C_torch_orgqr`, self, input2)
}

C_torch_lgamma <- function(self) {
    .Call(`_Rtorch_C_torch_lgamma`, self)
}

C_torch_digamma <- function(self) {
    .Call(`_Rtorch_C_torch_digamma`, self)
}

C_torch_erfinv <- function(self) {
    .Call(`_Rtorch_C_torch_erfinv`, self)
}

C_torch_i0 <- function(self) {
    .Call(`_Rtorch_C_torch_i0`, self)
}

C_torch_signbit <- function(self) {
    .Call(`_Rtorch_C_torch_signbit`, self)
}

C_torch_dist <- function(self, other, p_sexp) {
    .Call(`_Rtorch_C_torch_dist`, self, other, p_sexp)
}

C_torch_atan2 <- function(self, other) {
    .Call(`_Rtorch_C_torch_atan2`, self, other)
}

C_torch_arctan2 <- function(self, other) {
    .Call(`_Rtorch_C_torch_arctan2`, self, other)
}

C_torch_lerp <- function(self, end, weight_sexp) {
    .Call(`_Rtorch_C_torch_lerp`, self, end, weight_sexp)
}

C_torch_fmod <- function(self, other) {
    .Call(`_Rtorch_C_torch_fmod`, self, other)
}

C_torch_hypot <- function(self, other) {
    .Call(`_Rtorch_C_torch_hypot`, self, other)
}

C_torch_igamma <- function(self, other) {
    .Call(`_Rtorch_C_torch_igamma`, self, other)
}

C_torch_igammac <- function(self, other) {
    .Call(`_Rtorch_C_torch_igammac`, self, other)
}

C_torch_nextafter <- function(self, other) {
    .Call(`_Rtorch_C_torch_nextafter`, self, other)
}

C_torch_fmin <- function(self, other) {
    .Call(`_Rtorch_C_torch_fmin`, self, other)
}

C_torch_fmax <- function(self, other) {
    .Call(`_Rtorch_C_torch_fmax`, self, other)
}

C_torch_minimum <- function(self, other) {
    .Call(`_Rtorch_C_torch_minimum`, self, other)
}

C_torch_msort <- function(self) {
    .Call(`_Rtorch_C_torch_msort`, self)
}

C_torch_argsort <- function(self, dim, descending) {
    .Call(`_Rtorch_C_torch_argsort`, self, dim, descending)
}

C_torch_float_power <- function(self, exponent) {
    .Call(`_Rtorch_C_torch_float_power`, self, exponent)
}

C_torch_alias <- function(self) {
    .Call(`_Rtorch_C_torch_alias`, self)
}

C_torch_glu <- function(self, dim) {
    .Call(`_Rtorch_C_torch_glu`, self, dim)
}

C_torch_hardsigmoid <- function(self) {
    .Call(`_Rtorch_C_torch_hardsigmoid`, self)
}

C_torch_hardswish <- function(self) {
    .Call(`_Rtorch_C_torch_hardswish`, self)
}

C_torch_leaky_relu <- function(self, other) {
    .Call(`_Rtorch_C_torch_leaky_relu`, self, other)
}

C_torch_log_sigmoid <- function(self) {
    .Call(`_Rtorch_C_torch_log_sigmoid`, self)
}

C_torch_softshrink <- function(self, other) {
    .Call(`_Rtorch_C_torch_softshrink`, self, other)
}

C_torch_isfinite <- function(self) {
    .Call(`_Rtorch_C_torch_isfinite`, self)
}

C_torch_isinf <- function(self) {
    .Call(`_Rtorch_C_torch_isinf`, self)
}

C_torch_isposinf <- function(self) {
    .Call(`_Rtorch_C_torch_isposinf`, self)
}

C_torch_isneginf <- function(self) {
    .Call(`_Rtorch_C_torch_isneginf`, self)
}

C_torch_special_entr <- function(self) {
    .Call(`_Rtorch_C_torch_special_entr`, self)
}

C_torch_special_ndtri <- function(self) {
    .Call(`_Rtorch_C_torch_special_ndtri`, self)
}

C_torch_special_log_ndtr <- function(self) {
    .Call(`_Rtorch_C_torch_special_log_ndtr`, self)
}

C_torch_special_expm1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_expm1`, self)
}

C_torch_special_exp2 <- function(self) {
    .Call(`_Rtorch_C_torch_special_exp2`, self)
}

C_torch_special_psi <- function(self) {
    .Call(`_Rtorch_C_torch_special_psi`, self)
}

C_torch_special_digamma <- function(self) {
    .Call(`_Rtorch_C_torch_special_digamma`, self)
}

C_torch_special_gammaln <- function(self) {
    .Call(`_Rtorch_C_torch_special_gammaln`, self)
}

C_torch_special_erf <- function(self) {
    .Call(`_Rtorch_C_torch_special_erf`, self)
}

C_torch_special_erfc <- function(self) {
    .Call(`_Rtorch_C_torch_special_erfc`, self)
}

C_torch_special_erfcx <- function(self) {
    .Call(`_Rtorch_C_torch_special_erfcx`, self)
}

C_torch_special_erfinv <- function(self) {
    .Call(`_Rtorch_C_torch_special_erfinv`, self)
}

C_torch_special_ndtr <- function(self) {
    .Call(`_Rtorch_C_torch_special_ndtr`, self)
}

C_torch_special_xlog1py <- function(self, other) {
    .Call(`_Rtorch_C_torch_special_xlog1py`, self, other)
}

C_torch_special_xlogy <- function(self, other) {
    .Call(`_Rtorch_C_torch_special_xlogy`, self, other)
}

C_torch_special_zeta <- function(self, other) {
    .Call(`_Rtorch_C_torch_special_zeta`, self, other)
}

C_torch_special_i0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_i0`, self)
}

C_torch_special_i0e <- function(self) {
    .Call(`_Rtorch_C_torch_special_i0e`, self)
}

C_torch_special_i1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_i1`, self)
}

C_torch_special_i1e <- function(self) {
    .Call(`_Rtorch_C_torch_special_i1e`, self)
}

C_torch_special_expit <- function(self) {
    .Call(`_Rtorch_C_torch_special_expit`, self)
}

C_torch_special_sinc <- function(self) {
    .Call(`_Rtorch_C_torch_special_sinc`, self)
}

C_torch_special_round <- function(self, decimals) {
    .Call(`_Rtorch_C_torch_special_round`, self, decimals)
}

C_torch_special_log1p <- function(self) {
    .Call(`_Rtorch_C_torch_special_log1p`, self)
}

C_torch_special_gammainc <- function(self, other) {
    .Call(`_Rtorch_C_torch_special_gammainc`, self, other)
}

C_torch_special_gammaincc <- function(self, other) {
    .Call(`_Rtorch_C_torch_special_gammaincc`, self, other)
}

C_torch_special_multigammaln <- function(self, p) {
    .Call(`_Rtorch_C_torch_special_multigammaln`, self, p)
}

C_torch_linalg_cholesky <- function(self, upper) {
    .Call(`_Rtorch_C_torch_linalg_cholesky`, self, upper)
}

C_torch_linalg_det <- function(self) {
    .Call(`_Rtorch_C_torch_linalg_det`, self)
}

C_torch_det <- function(self) {
    .Call(`_Rtorch_C_torch_det`, self)
}

C_torch_linalg_matmul <- function(self, other) {
    .Call(`_Rtorch_C_torch_linalg_matmul`, self, other)
}

C_torch_linalg_matrix_exp <- function(self) {
    .Call(`_Rtorch_C_torch_linalg_matrix_exp`, self)
}

C_torch_logdet <- function(self) {
    .Call(`_Rtorch_C_torch_logdet`, self)
}

C_torch_linalg_eigvals <- function(self) {
    .Call(`_Rtorch_C_torch_linalg_eigvals`, self)
}

C_torch_linalg_householder_product <- function(self, tau) {
    .Call(`_Rtorch_C_torch_linalg_householder_product`, self, tau)
}

C_torch_linalg_inv <- function(self) {
    .Call(`_Rtorch_C_torch_linalg_inv`, self)
}

C_torch_inverse <- function(self) {
    .Call(`_Rtorch_C_torch_inverse`, self)
}

C_torch_inner <- function(self, other) {
    .Call(`_Rtorch_C_torch_inner`, self, other)
}

C_torch_ger <- function(self, vec2) {
    .Call(`_Rtorch_C_torch_ger`, self, vec2)
}

C_torch_linalg_tensorinv <- function(self, ind) {
    .Call(`_Rtorch_C_torch_linalg_tensorinv`, self, ind)
}

C_torch_linalg_matrix_power <- function(self, n) {
    .Call(`_Rtorch_C_torch_linalg_matrix_power`, self, n)
}

C_torch_special_airy_ai <- function(self) {
    .Call(`_Rtorch_C_torch_special_airy_ai`, self)
}

C_torch_special_bessel_j0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_bessel_j0`, self)
}

C_torch_special_bessel_j1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_bessel_j1`, self)
}

C_torch_special_bessel_y0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_bessel_y0`, self)
}

C_torch_special_bessel_y1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_bessel_y1`, self)
}

C_torch_special_chebyshev_polynomial_t <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_chebyshev_polynomial_t`, self, n)
}

C_torch_special_chebyshev_polynomial_u <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_chebyshev_polynomial_u`, self, n)
}

C_torch_special_chebyshev_polynomial_v <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_chebyshev_polynomial_v`, self, n)
}

C_torch_special_chebyshev_polynomial_w <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_chebyshev_polynomial_w`, self, n)
}

C_torch_special_hermite_polynomial_h <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_hermite_polynomial_h`, self, n)
}

C_torch_special_hermite_polynomial_he <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_hermite_polynomial_he`, self, n)
}

C_torch_special_laguerre_polynomial_l <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_laguerre_polynomial_l`, self, n)
}

C_torch_special_legendre_polynomial_p <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_legendre_polynomial_p`, self, n)
}

C_torch_special_modified_bessel_i0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_modified_bessel_i0`, self)
}

C_torch_special_modified_bessel_i1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_modified_bessel_i1`, self)
}

C_torch_special_modified_bessel_k0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_modified_bessel_k0`, self)
}

C_torch_special_modified_bessel_k1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_modified_bessel_k1`, self)
}

C_torch_special_scaled_modified_bessel_k0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_scaled_modified_bessel_k0`, self)
}

C_torch_special_scaled_modified_bessel_k1 <- function(self) {
    .Call(`_Rtorch_C_torch_special_scaled_modified_bessel_k1`, self)
}

C_torch_special_shifted_chebyshev_polynomial_t <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_shifted_chebyshev_polynomial_t`, self, n)
}

C_torch_special_shifted_chebyshev_polynomial_u <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_shifted_chebyshev_polynomial_u`, self, n)
}

C_torch_special_shifted_chebyshev_polynomial_v <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_shifted_chebyshev_polynomial_v`, self, n)
}

C_torch_special_shifted_chebyshev_polynomial_w <- function(self, n) {
    .Call(`_Rtorch_C_torch_special_shifted_chebyshev_polynomial_w`, self, n)
}

C_torch_special_spherical_bessel_j0 <- function(self) {
    .Call(`_Rtorch_C_torch_special_spherical_bessel_j0`, self)
}

C_gpu_launch <- function(ptx_sexp, kernel_name_sexp, inputs_sexp, output_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch`, ptx_sexp, kernel_name_sexp, inputs_sexp, output_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_launch_reduction <- function(ptx_sexp, kernel_name_sexp, input_sexp, output_sexp, n_elements_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch_reduction`, ptx_sexp, kernel_name_sexp, input_sexp, output_sexp, n_elements_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_launch_generic <- function(ptx_sexp, kernel_name_sexp, tensors_sexp, scalars_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch_generic`, ptx_sexp, kernel_name_sexp, tensors_sexp, scalars_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_kernel_cache_clear <- function() {
    .Call(`_Rtorch_C_gpu_kernel_cache_clear`)
}

C_gpu_kernel_cache_stats <- function() {
    .Call(`_Rtorch_C_gpu_kernel_cache_stats`)
}

C_torch_index <- function(self_sexp, indices_list, drop_sexp) {
    .Call(`_Rtorch_C_torch_index`, self_sexp, indices_list, drop_sexp)
}

C_torch_index_put <- function(self_sexp, indices_list, value_sexp) {
    .Call(`_Rtorch_C_torch_index_put`, self_sexp, indices_list, value_sexp)
}

C_nnf_silu <- function(self) {
    .Call(`_Rtorch_C_nnf_silu`, self)
}

C_nnf_gelu <- function(self, approximate_sexp) {
    .Call(`_Rtorch_C_nnf_gelu`, self, approximate_sexp)
}

C_nnf_leaky_relu <- function(self, negative_slope_sexp) {
    .Call(`_Rtorch_C_nnf_leaky_relu`, self, negative_slope_sexp)
}

C_nnf_elu <- function(self, alpha_sexp) {
    .Call(`_Rtorch_C_nnf_elu`, self, alpha_sexp)
}

C_nnf_softmax <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_nnf_softmax`, self, dim_sexp)
}

C_nnf_log_softmax <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_nnf_log_softmax`, self, dim_sexp)
}

C_nnf_layer_norm <- function(self, normalized_shape_sexp, weight, bias, eps_sexp) {
    .Call(`_Rtorch_C_nnf_layer_norm`, self, normalized_shape_sexp, weight, bias, eps_sexp)
}

C_torch_linear <- function(input, weight, bias) {
    .Call(`_Rtorch_C_torch_linear`, input, weight, bias)
}

C_torch_conv1d <- function(input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp) {
    .Call(`_Rtorch_C_torch_conv1d`, input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp)
}

C_torch_embedding <- function(weight, indices) {
    .Call(`_Rtorch_C_torch_embedding`, weight, indices)
}

C_torch_conv_transpose1d <- function(input, weight, bias, stride_sexp, padding_sexp, output_padding_sexp, groups_sexp, dilation_sexp) {
    .Call(`_Rtorch_C_torch_conv_transpose1d`, input, weight, bias, stride_sexp, padding_sexp, output_padding_sexp, groups_sexp, dilation_sexp)
}

C_torch_conv2d <- function(input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp) {
    .Call(`_Rtorch_C_torch_conv2d`, input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp)
}

C_torch_batch_norm <- function(input, weight, bias, running_mean, running_var, training_sexp, momentum_sexp, eps_sexp, cudnn_enabled_sexp) {
    .Call(`_Rtorch_C_torch_batch_norm`, input, weight, bias, running_mean, running_var, training_sexp, momentum_sexp, eps_sexp, cudnn_enabled_sexp)
}

C_torch_lstm <- function(input, hx_sexp, params_sexp, has_biases_sexp, num_layers_sexp, dropout_sexp, batch_first_sexp, bidirectional_sexp) {
    .Call(`_Rtorch_C_torch_lstm`, input, hx_sexp, params_sexp, has_biases_sexp, num_layers_sexp, dropout_sexp, batch_first_sexp, bidirectional_sexp)
}

C_nnf_pad <- function(input, pad_sexp, mode_sexp, value_sexp) {
    .Call(`_Rtorch_C_nnf_pad`, input, pad_sexp, mode_sexp, value_sexp)
}

C_nnf_interpolate <- function(input, size_sexp, scale_factor_sexp, mode_sexp, align_corners_sexp) {
    .Call(`_Rtorch_C_nnf_interpolate`, input, size_sexp, scale_factor_sexp, mode_sexp, align_corners_sexp)
}

C_nnf_avg_pool1d <- function(input, kernel_size_sexp, stride_sexp, padding_sexp, ceil_mode_sexp, count_include_pad_sexp) {
    .Call(`_Rtorch_C_nnf_avg_pool1d`, input, kernel_size_sexp, stride_sexp, padding_sexp, ceil_mode_sexp, count_include_pad_sexp)
}

C_nnf_softplus <- function(input, beta_sexp, threshold_sexp) {
    .Call(`_Rtorch_C_nnf_softplus`, input, beta_sexp, threshold_sexp)
}

C_nnf_normalize <- function(input, p_sexp, dim_sexp, eps_sexp) {
    .Call(`_Rtorch_C_nnf_normalize`, input, p_sexp, dim_sexp, eps_sexp)
}

C_torch_sdpa <- function(query, key, value, attn_mask_sexp, dropout_sexp, is_causal_sexp) {
    .Call(`_Rtorch_C_torch_sdpa`, query, key, value, attn_mask_sexp, dropout_sexp, is_causal_sexp)
}

C_torch_add <- function(self, other, alpha) {
    .Call(`_Rtorch_C_torch_add`, self, other, alpha)
}

C_torch_sub <- function(self, other, alpha) {
    .Call(`_Rtorch_C_torch_sub`, self, other, alpha)
}

C_torch_mul <- function(self, other) {
    .Call(`_Rtorch_C_torch_mul`, self, other)
}

C_torch_div <- function(self, other) {
    .Call(`_Rtorch_C_torch_div`, self, other)
}

C_torch_neg <- function(self) {
    .Call(`_Rtorch_C_torch_neg`, self)
}

C_torch_logical_not <- function(self) {
    .Call(`_Rtorch_C_torch_logical_not`, self)
}

C_torch_add_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_add_scalar`, self, scalar)
}

C_torch_sub_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_sub_scalar`, self, scalar)
}

C_torch_mul_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_mul_scalar`, self, scalar)
}

C_torch_div_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_div_scalar`, self, scalar)
}

C_torch_matmul <- function(self, other) {
    .Call(`_Rtorch_C_torch_matmul`, self, other)
}

C_torch_mm <- function(self, other) {
    .Call(`_Rtorch_C_torch_mm`, self, other)
}

C_torch_t <- function(self) {
    .Call(`_Rtorch_C_torch_t`, self)
}

C_torch_sum <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_sum`, self, dim_sexp, keepdim_sexp)
}

C_torch_mean <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_mean`, self, dim_sexp, keepdim_sexp)
}

C_torch_max <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_max`, self, dim_sexp)
}

C_torch_min <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_min`, self, dim_sexp)
}

C_torch_argmax <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_argmax`, self, dim_sexp, keepdim_sexp)
}

C_torch_argmin <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_argmin`, self, dim_sexp, keepdim_sexp)
}

C_torch_reshape <- function(self, shape_sexp) {
    .Call(`_Rtorch_C_torch_reshape`, self, shape_sexp)
}

C_torch_view <- function(self, shape_sexp) {
    .Call(`_Rtorch_C_torch_view`, self, shape_sexp)
}

C_torch_squeeze <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_squeeze`, self, dim_sexp)
}

C_torch_unsqueeze <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_unsqueeze`, self, dim_sexp)
}

C_torch_relu <- function(self) {
    .Call(`_Rtorch_C_torch_relu`, self)
}

C_torch_sigmoid <- function(self) {
    .Call(`_Rtorch_C_torch_sigmoid`, self)
}

C_torch_tanh <- function(self) {
    .Call(`_Rtorch_C_torch_tanh`, self)
}

C_torch_exp <- function(self) {
    .Call(`_Rtorch_C_torch_exp`, self)
}

C_torch_log <- function(self) {
    .Call(`_Rtorch_C_torch_log`, self)
}

C_torch_log2 <- function(self) {
    .Call(`_Rtorch_C_torch_log2`, self)
}

C_torch_log10 <- function(self) {
    .Call(`_Rtorch_C_torch_log10`, self)
}

C_torch_sqrt <- function(self) {
    .Call(`_Rtorch_C_torch_sqrt`, self)
}

C_torch_abs <- function(self) {
    .Call(`_Rtorch_C_torch_abs`, self)
}

C_torch_sign <- function(self) {
    .Call(`_Rtorch_C_torch_sign`, self)
}

C_torch_floor <- function(self) {
    .Call(`_Rtorch_C_torch_floor`, self)
}

C_torch_ceil <- function(self) {
    .Call(`_Rtorch_C_torch_ceil`, self)
}

C_torch_round <- function(self) {
    .Call(`_Rtorch_C_torch_round`, self)
}

C_torch_trunc <- function(self) {
    .Call(`_Rtorch_C_torch_trunc`, self)
}

C_torch_sin <- function(self) {
    .Call(`_Rtorch_C_torch_sin`, self)
}

C_torch_cos <- function(self) {
    .Call(`_Rtorch_C_torch_cos`, self)
}

C_torch_rsqrt <- function(self) {
    .Call(`_Rtorch_C_torch_rsqrt`, self)
}

C_torch_detach <- function(self) {
    .Call(`_Rtorch_C_torch_detach`, self)
}

C_torch_pow <- function(self, other) {
    .Call(`_Rtorch_C_torch_pow`, self, other)
}

C_torch_pow_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_pow_scalar`, self, scalar)
}

C_torch_scalar_pow <- function(scalar, exponent) {
    .Call(`_Rtorch_C_torch_scalar_pow`, scalar, exponent)
}

C_torch_remainder <- function(self, other) {
    .Call(`_Rtorch_C_torch_remainder`, self, other)
}

C_torch_remainder_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_remainder_scalar`, self, scalar)
}

C_torch_floor_divide <- function(self, other) {
    .Call(`_Rtorch_C_torch_floor_divide`, self, other)
}

C_torch_floor_divide_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_floor_divide_scalar`, self, scalar)
}

C_torch_eq <- function(self, other) {
    .Call(`_Rtorch_C_torch_eq`, self, other)
}

C_torch_eq_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_eq_scalar`, self, scalar)
}

C_torch_ne <- function(self, other) {
    .Call(`_Rtorch_C_torch_ne`, self, other)
}

C_torch_ne_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_ne_scalar`, self, scalar)
}

C_torch_lt <- function(self, other) {
    .Call(`_Rtorch_C_torch_lt`, self, other)
}

C_torch_lt_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_lt_scalar`, self, scalar)
}

C_torch_le <- function(self, other) {
    .Call(`_Rtorch_C_torch_le`, self, other)
}

C_torch_le_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_le_scalar`, self, scalar)
}

C_torch_gt <- function(self, other) {
    .Call(`_Rtorch_C_torch_gt`, self, other)
}

C_torch_gt_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_gt_scalar`, self, scalar)
}

C_torch_ge <- function(self, other) {
    .Call(`_Rtorch_C_torch_ge`, self, other)
}

C_torch_ge_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_ge_scalar`, self, scalar)
}

C_torch_bmm <- function(self, other) {
    .Call(`_Rtorch_C_torch_bmm`, self, other)
}

C_torch_transpose <- function(self, dim0_sexp, dim1_sexp) {
    .Call(`_Rtorch_C_torch_transpose`, self, dim0_sexp, dim1_sexp)
}

C_torch_flatten <- function(self, start_dim_sexp, end_dim_sexp) {
    .Call(`_Rtorch_C_torch_flatten`, self, start_dim_sexp, end_dim_sexp)
}

C_torch_clone <- function(self) {
    .Call(`_Rtorch_C_torch_clone`, self)
}

C_torch_contiguous <- function(self) {
    .Call(`_Rtorch_C_torch_contiguous`, self)
}

C_torch_to_dtype <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_to_dtype`, self, dtype_sexp)
}

C_torch_item <- function(self) {
    .Call(`_Rtorch_C_torch_item`, self)
}

C_torch_cat <- function(tensors_sexp, dim_sexp) {
    .Call(`_Rtorch_C_torch_cat`, tensors_sexp, dim_sexp)
}

C_torch_clamp <- function(self, min_sexp, max_sexp) {
    .Call(`_Rtorch_C_torch_clamp`, self, min_sexp, max_sexp)
}

C_torch_where <- function(condition, self, other) {
    .Call(`_Rtorch_C_torch_where`, condition, self, other)
}

C_torch_sort <- function(self, dim_sexp, descending_sexp) {
    .Call(`_Rtorch_C_torch_sort`, self, dim_sexp, descending_sexp)
}

C_torch_flip <- function(self, dims_sexp) {
    .Call(`_Rtorch_C_torch_flip`, self, dims_sexp)
}

C_torch_cumsum <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_cumsum`, self, dim_sexp)
}

C_torch_maximum <- function(self, other) {
    .Call(`_Rtorch_C_torch_maximum`, self, other)
}

C_torch_multinomial <- function(self, num_samples_sexp, replacement_sexp) {
    .Call(`_Rtorch_C_torch_multinomial`, self, num_samples_sexp, replacement_sexp)
}

C_torch_outer <- function(self, vec2) {
    .Call(`_Rtorch_C_torch_outer`, self, vec2)
}

C_torch_triu <- function(self, diagonal_sexp) {
    .Call(`_Rtorch_C_torch_triu`, self, diagonal_sexp)
}

C_torch_norm <- function(self, p_sexp, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_norm`, self, p_sexp, dim_sexp, keepdim_sexp)
}

C_torch_std <- function(self, dim_sexp, keepdim_sexp, correction_sexp) {
    .Call(`_Rtorch_C_torch_std`, self, dim_sexp, keepdim_sexp, correction_sexp)
}

C_torch_complex <- function(real, imag) {
    .Call(`_Rtorch_C_torch_complex`, real, imag)
}

C_torch_real <- function(self) {
    .Call(`_Rtorch_C_torch_real`, self)
}

C_torch_imag <- function(self) {
    .Call(`_Rtorch_C_torch_imag`, self)
}

C_torch_polar <- function(abs, angle) {
    .Call(`_Rtorch_C_torch_polar`, abs, angle)
}

C_torch_view_as_real <- function(self) {
    .Call(`_Rtorch_C_torch_view_as_real`, self)
}

C_torch_stft <- function(input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, return_complex_sexp) {
    .Call(`_Rtorch_C_torch_stft`, input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, return_complex_sexp)
}

C_torch_istft <- function(input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, length_sexp, return_complex_sexp) {
    .Call(`_Rtorch_C_torch_istft`, input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, length_sexp, return_complex_sexp)
}

C_torch_hann_window <- function(length_sexp, periodic_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_hann_window`, length_sexp, periodic_sexp, dtype_sexp, device_sexp)
}

C_torch_tensor <- function(data, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_tensor`, data, dtype_sexp, device_sexp)
}

C_torch_tensor_raw <- function(data, dim_sexp, dtype_sexp) {
    .Call(`_Rtorch_C_torch_tensor_raw`, data, dim_sexp, dtype_sexp)
}

C_torch_zeros <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_zeros`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_ones <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_ones`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_randn <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_randn`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_empty_like <- function(self) {
    .Call(`_Rtorch_C_torch_empty_like`, self)
}

C_torch_empty <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_empty`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_tensor_from_buffer <- function(raw_sexp, shape_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_tensor_from_buffer`, raw_sexp, shape_sexp, dtype_sexp, device_sexp)
}

C_torch_arange <- function(start_sexp, end_sexp, step_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_arange`, start_sexp, end_sexp, step_sexp, dtype_sexp, device_sexp)
}

C_torch_full <- function(size_sexp, fill_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_full`, size_sexp, fill_sexp, dtype_sexp, device_sexp)
}

C_torch_linspace <- function(start_sexp, end_sexp, steps_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_linspace`, start_sexp, end_sexp, steps_sexp, dtype_sexp, device_sexp)
}

C_torch_ones_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_ones_like`, self, dtype_sexp)
}

C_torch_zeros_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_zeros_like`, self, dtype_sexp)
}

C_torch_randn_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_randn_like`, self, dtype_sexp)
}

C_torch_permute <- function(self, dims_sexp) {
    .Call(`_Rtorch_C_torch_permute`, self, dims_sexp)
}

C_torch_expand <- function(self, size_sexp) {
    .Call(`_Rtorch_C_torch_expand`, self, size_sexp)
}

C_torch_gather <- function(self, dim_sexp, index) {
    .Call(`_Rtorch_C_torch_gather`, self, dim_sexp, index)
}

C_torch_masked_fill <- function(self, mask, value_sexp) {
    .Call(`_Rtorch_C_torch_masked_fill`, self, mask, value_sexp)
}

C_torch_masked_fill_ <- function(self, mask, value_sexp) {
    .Call(`_Rtorch_C_torch_masked_fill_`, self, mask, value_sexp)
}

C_torch_copy_ <- function(self, src) {
    .Call(`_Rtorch_C_torch_copy_`, self, src)
}

C_torch_normal_ <- function(self, mean_sexp, std_sexp) {
    .Call(`_Rtorch_C_torch_normal_`, self, mean_sexp, std_sexp)
}

C_torch_uniform_ <- function(self, from_sexp, to_sexp) {
    .Call(`_Rtorch_C_torch_uniform_`, self, from_sexp, to_sexp)
}

C_torch_zero_ <- function(self) {
    .Call(`_Rtorch_C_torch_zero_`, self)
}

C_torch_fill_ <- function(self, value_sexp) {
    .Call(`_Rtorch_C_torch_fill_`, self, value_sexp)
}

C_torch_repeat <- function(self, sizes_sexp) {
    .Call(`_Rtorch_C_torch_repeat`, self, sizes_sexp)
}

C_torch_repeat_interleave <- function(self, repeats_sexp, dim_sexp) {
    .Call(`_Rtorch_C_torch_repeat_interleave`, self, repeats_sexp, dim_sexp)
}

C_torch_index_select <- function(self, dim_sexp, index) {
    .Call(`_Rtorch_C_torch_index_select`, self, dim_sexp, index)
}

C_torch_narrow <- function(self, dim_sexp, start_sexp, length_sexp) {
    .Call(`_Rtorch_C_torch_narrow`, self, dim_sexp, start_sexp, length_sexp)
}

C_torch_scatter_ <- function(self, dim_sexp, index, src) {
    .Call(`_Rtorch_C_torch_scatter_`, self, dim_sexp, index, src)
}

C_tensor_to_device <- function(self, device_sexp) {
    .Call(`_Rtorch_C_tensor_to_device`, self, device_sexp)
}

C_tensor_to_dtype_device <- function(self, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_tensor_to_dtype_device`, self, dtype_sexp, device_sexp)
}

C_torch_set_num_threads <- function(n_sexp) {
    .Call(`_Rtorch_C_torch_set_num_threads`, n_sexp)
}

C_torch_get_num_threads <- function() {
    .Call(`_Rtorch_C_torch_get_num_threads`)
}

C_torch_set_num_interop_threads <- function(n_sexp) {
    .Call(`_Rtorch_C_torch_set_num_interop_threads`, n_sexp)
}

C_torch_get_num_interop_threads <- function() {
    .Call(`_Rtorch_C_torch_get_num_interop_threads`)
}

C_cuda_is_available <- function() {
    .Call(`_Rtorch_C_cuda_is_available`)
}

C_cuda_device_count <- function() {
    .Call(`_Rtorch_C_cuda_device_count`)
}

C_cuda_empty_cache <- function() {
    .Call(`_Rtorch_C_cuda_empty_cache`)
}

C_cuda_mem_info <- function() {
    .Call(`_Rtorch_C_cuda_mem_info`)
}

C_cuda_memory_stats <- function() {
    .Call(`_Rtorch_C_cuda_memory_stats`)
}

C_transformer_decoder_layer_step <- function(x_sexp, weights_sexp, self_cache_k_sexp, self_cache_v_sexp, cross_cache_k_sexp, cross_cache_v_sexp, n_head_sexp) {
    .Call(`_Rtorch_C_transformer_decoder_layer_step`, x_sexp, weights_sexp, self_cache_k_sexp, self_cache_v_sexp, cross_cache_k_sexp, cross_cache_v_sexp, n_head_sexp)
}

C_transformer_encoder_layer <- function(x_sexp, weights_sexp, n_head_sexp) {
    .Call(`_Rtorch_C_transformer_encoder_layer`, x_sexp, weights_sexp, n_head_sexp)
}

C_prepare_cross_caches <- function(encoder_output_sexp, cross_kv_weights, n_head_sexp) {
    .Call(`_Rtorch_C_prepare_cross_caches`, encoder_output_sexp, cross_kv_weights, n_head_sexp)
}

C_encoder_forward <- function(mel_sexp, global_weights, layer_weights, n_head_sexp, n_ctx_sexp) {
    .Call(`_Rtorch_C_encoder_forward`, mel_sexp, global_weights, layer_weights, n_head_sexp, n_ctx_sexp)
}

C_decoder_forward_step <- function(token_ids_sexp, global_weights, layer_weights, self_cache_k_list, self_cache_v_list, cross_cache_k_list, cross_cache_v_list, n_head_sexp, offset_sexp) {
    .Call(`_Rtorch_C_decoder_forward_step`, token_ids_sexp, global_weights, layer_weights, self_cache_k_list, self_cache_v_list, cross_cache_k_list, cross_cache_v_list, n_head_sexp, offset_sexp)
}

C_greedy_decode <- function(initial_tokens_sexp, global_weights, layer_weights, cross_cache_k_list, cross_cache_v_list, n_head_sexp, max_length_sexp, eot_token_sexp) {
    .Call(`_Rtorch_C_greedy_decode`, initial_tokens_sexp, global_weights, layer_weights, cross_cache_k_list, cross_cache_v_list, n_head_sexp, max_length_sexp, eot_token_sexp)
}

