# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_as_array <- function(self) {
    .Call(`_Rtorch_C_as_array`, self)
}

C_tensor_shape <- function(self) {
    .Call(`_Rtorch_C_tensor_shape`, self)
}

C_tensor_dtype <- function(self) {
    .Call(`_Rtorch_C_tensor_dtype`, self)
}

C_tensor_device <- function(self) {
    .Call(`_Rtorch_C_tensor_device`, self)
}

C_tensor_ndim <- function(self) {
    .Call(`_Rtorch_C_tensor_ndim`, self)
}

C_tensor_numel <- function(self) {
    .Call(`_Rtorch_C_tensor_numel`, self)
}

C_tensor_requires_grad <- function(self) {
    .Call(`_Rtorch_C_tensor_requires_grad`, self)
}

C_tensor_print <- function(self) {
    .Call(`_Rtorch_C_tensor_print`, self)
}

cpp_fused_relu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu`, input_sexp)
}

cpp_fused_relu_sigmoid <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu_sigmoid`, input_sexp)
}

cpp_fused_relu_sigmoid_tanh <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_relu_sigmoid_tanh`, input_sexp)
}

cpp_fused_silu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_silu`, input_sexp)
}

cpp_fused_gelu <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_gelu`, input_sexp)
}

cpp_fused_sincos <- function(input_sexp) {
    .Call(`_Rtorch_cpp_fused_sincos`, input_sexp)
}

cpp_fused_softcap <- function(input_sexp, cap_sexp) {
    .Call(`_Rtorch_cpp_fused_softcap`, input_sexp, cap_sexp)
}

cpp_fused_rmsnorm <- function(input_sexp, weight_sexp, eps_sexp) {
    .Call(`_Rtorch_cpp_fused_rmsnorm`, input_sexp, weight_sexp, eps_sexp)
}

cpp_tensor_shapes_key <- function(tensor_list) {
    .Call(`_Rtorch_cpp_tensor_shapes_key`, tensor_list)
}

C_gpu_launch <- function(ptx_sexp, kernel_name_sexp, inputs_sexp, output_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch`, ptx_sexp, kernel_name_sexp, inputs_sexp, output_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_launch_reduction <- function(ptx_sexp, kernel_name_sexp, input_sexp, output_sexp, n_elements_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch_reduction`, ptx_sexp, kernel_name_sexp, input_sexp, output_sexp, n_elements_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_launch_generic <- function(ptx_sexp, kernel_name_sexp, tensors_sexp, scalars_sexp, grid_sexp, block_sexp, shared_mem_sexp) {
    .Call(`_Rtorch_C_gpu_launch_generic`, ptx_sexp, kernel_name_sexp, tensors_sexp, scalars_sexp, grid_sexp, block_sexp, shared_mem_sexp)
}

C_gpu_kernel_cache_clear <- function() {
    .Call(`_Rtorch_C_gpu_kernel_cache_clear`)
}

C_gpu_kernel_cache_stats <- function() {
    .Call(`_Rtorch_C_gpu_kernel_cache_stats`)
}

C_torch_index <- function(self_sexp, indices_list, drop_sexp) {
    .Call(`_Rtorch_C_torch_index`, self_sexp, indices_list, drop_sexp)
}

C_torch_index_put <- function(self_sexp, indices_list, value_sexp) {
    .Call(`_Rtorch_C_torch_index_put`, self_sexp, indices_list, value_sexp)
}

C_nnf_silu <- function(self) {
    .Call(`_Rtorch_C_nnf_silu`, self)
}

C_nnf_gelu <- function(self, approximate_sexp) {
    .Call(`_Rtorch_C_nnf_gelu`, self, approximate_sexp)
}

C_nnf_leaky_relu <- function(self, negative_slope_sexp) {
    .Call(`_Rtorch_C_nnf_leaky_relu`, self, negative_slope_sexp)
}

C_nnf_elu <- function(self, alpha_sexp) {
    .Call(`_Rtorch_C_nnf_elu`, self, alpha_sexp)
}

C_nnf_softmax <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_nnf_softmax`, self, dim_sexp)
}

C_nnf_log_softmax <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_nnf_log_softmax`, self, dim_sexp)
}

C_nnf_layer_norm <- function(self, normalized_shape_sexp, weight, bias, eps_sexp) {
    .Call(`_Rtorch_C_nnf_layer_norm`, self, normalized_shape_sexp, weight, bias, eps_sexp)
}

C_torch_linear <- function(input, weight, bias) {
    .Call(`_Rtorch_C_torch_linear`, input, weight, bias)
}

C_torch_conv1d <- function(input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp) {
    .Call(`_Rtorch_C_torch_conv1d`, input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp)
}

C_torch_embedding <- function(weight, indices) {
    .Call(`_Rtorch_C_torch_embedding`, weight, indices)
}

C_torch_conv_transpose1d <- function(input, weight, bias, stride_sexp, padding_sexp, output_padding_sexp, groups_sexp, dilation_sexp) {
    .Call(`_Rtorch_C_torch_conv_transpose1d`, input, weight, bias, stride_sexp, padding_sexp, output_padding_sexp, groups_sexp, dilation_sexp)
}

C_torch_conv2d <- function(input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp) {
    .Call(`_Rtorch_C_torch_conv2d`, input, weight, bias, stride_sexp, padding_sexp, dilation_sexp, groups_sexp)
}

C_torch_batch_norm <- function(input, weight, bias, running_mean, running_var, training_sexp, momentum_sexp, eps_sexp, cudnn_enabled_sexp) {
    .Call(`_Rtorch_C_torch_batch_norm`, input, weight, bias, running_mean, running_var, training_sexp, momentum_sexp, eps_sexp, cudnn_enabled_sexp)
}

C_torch_lstm <- function(input, hx_sexp, params_sexp, has_biases_sexp, num_layers_sexp, dropout_sexp, batch_first_sexp, bidirectional_sexp) {
    .Call(`_Rtorch_C_torch_lstm`, input, hx_sexp, params_sexp, has_biases_sexp, num_layers_sexp, dropout_sexp, batch_first_sexp, bidirectional_sexp)
}

C_nnf_pad <- function(input, pad_sexp, mode_sexp, value_sexp) {
    .Call(`_Rtorch_C_nnf_pad`, input, pad_sexp, mode_sexp, value_sexp)
}

C_nnf_interpolate <- function(input, size_sexp, scale_factor_sexp, mode_sexp, align_corners_sexp) {
    .Call(`_Rtorch_C_nnf_interpolate`, input, size_sexp, scale_factor_sexp, mode_sexp, align_corners_sexp)
}

C_nnf_avg_pool1d <- function(input, kernel_size_sexp, stride_sexp, padding_sexp, ceil_mode_sexp, count_include_pad_sexp) {
    .Call(`_Rtorch_C_nnf_avg_pool1d`, input, kernel_size_sexp, stride_sexp, padding_sexp, ceil_mode_sexp, count_include_pad_sexp)
}

C_nnf_softplus <- function(input, beta_sexp, threshold_sexp) {
    .Call(`_Rtorch_C_nnf_softplus`, input, beta_sexp, threshold_sexp)
}

C_nnf_normalize <- function(input, p_sexp, dim_sexp, eps_sexp) {
    .Call(`_Rtorch_C_nnf_normalize`, input, p_sexp, dim_sexp, eps_sexp)
}

C_torch_sdpa <- function(query, key, value, attn_mask_sexp, dropout_sexp, is_causal_sexp) {
    .Call(`_Rtorch_C_torch_sdpa`, query, key, value, attn_mask_sexp, dropout_sexp, is_causal_sexp)
}

C_torch_add <- function(self, other, alpha) {
    .Call(`_Rtorch_C_torch_add`, self, other, alpha)
}

C_torch_sub <- function(self, other, alpha) {
    .Call(`_Rtorch_C_torch_sub`, self, other, alpha)
}

C_torch_mul <- function(self, other) {
    .Call(`_Rtorch_C_torch_mul`, self, other)
}

C_torch_div <- function(self, other) {
    .Call(`_Rtorch_C_torch_div`, self, other)
}

C_torch_neg <- function(self) {
    .Call(`_Rtorch_C_torch_neg`, self)
}

C_torch_logical_not <- function(self) {
    .Call(`_Rtorch_C_torch_logical_not`, self)
}

C_torch_add_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_add_scalar`, self, scalar)
}

C_torch_sub_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_sub_scalar`, self, scalar)
}

C_torch_mul_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_mul_scalar`, self, scalar)
}

C_torch_div_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_div_scalar`, self, scalar)
}

C_torch_matmul <- function(self, other) {
    .Call(`_Rtorch_C_torch_matmul`, self, other)
}

C_torch_mm <- function(self, other) {
    .Call(`_Rtorch_C_torch_mm`, self, other)
}

C_torch_t <- function(self) {
    .Call(`_Rtorch_C_torch_t`, self)
}

C_torch_sum <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_sum`, self, dim_sexp, keepdim_sexp)
}

C_torch_mean <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_mean`, self, dim_sexp, keepdim_sexp)
}

C_torch_max <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_max`, self, dim_sexp)
}

C_torch_min <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_min`, self, dim_sexp)
}

C_torch_argmax <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_argmax`, self, dim_sexp, keepdim_sexp)
}

C_torch_argmin <- function(self, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_argmin`, self, dim_sexp, keepdim_sexp)
}

C_torch_reshape <- function(self, shape_sexp) {
    .Call(`_Rtorch_C_torch_reshape`, self, shape_sexp)
}

C_torch_view <- function(self, shape_sexp) {
    .Call(`_Rtorch_C_torch_view`, self, shape_sexp)
}

C_torch_squeeze <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_squeeze`, self, dim_sexp)
}

C_torch_unsqueeze <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_unsqueeze`, self, dim_sexp)
}

C_torch_relu <- function(self) {
    .Call(`_Rtorch_C_torch_relu`, self)
}

C_torch_sigmoid <- function(self) {
    .Call(`_Rtorch_C_torch_sigmoid`, self)
}

C_torch_tanh <- function(self) {
    .Call(`_Rtorch_C_torch_tanh`, self)
}

C_torch_exp <- function(self) {
    .Call(`_Rtorch_C_torch_exp`, self)
}

C_torch_log <- function(self) {
    .Call(`_Rtorch_C_torch_log`, self)
}

C_torch_log2 <- function(self) {
    .Call(`_Rtorch_C_torch_log2`, self)
}

C_torch_log10 <- function(self) {
    .Call(`_Rtorch_C_torch_log10`, self)
}

C_torch_sqrt <- function(self) {
    .Call(`_Rtorch_C_torch_sqrt`, self)
}

C_torch_abs <- function(self) {
    .Call(`_Rtorch_C_torch_abs`, self)
}

C_torch_sign <- function(self) {
    .Call(`_Rtorch_C_torch_sign`, self)
}

C_torch_floor <- function(self) {
    .Call(`_Rtorch_C_torch_floor`, self)
}

C_torch_ceil <- function(self) {
    .Call(`_Rtorch_C_torch_ceil`, self)
}

C_torch_round <- function(self) {
    .Call(`_Rtorch_C_torch_round`, self)
}

C_torch_trunc <- function(self) {
    .Call(`_Rtorch_C_torch_trunc`, self)
}

C_torch_sin <- function(self) {
    .Call(`_Rtorch_C_torch_sin`, self)
}

C_torch_cos <- function(self) {
    .Call(`_Rtorch_C_torch_cos`, self)
}

C_torch_rsqrt <- function(self) {
    .Call(`_Rtorch_C_torch_rsqrt`, self)
}

C_torch_detach <- function(self) {
    .Call(`_Rtorch_C_torch_detach`, self)
}

C_torch_pow <- function(self, other) {
    .Call(`_Rtorch_C_torch_pow`, self, other)
}

C_torch_pow_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_pow_scalar`, self, scalar)
}

C_torch_scalar_pow <- function(scalar, exponent) {
    .Call(`_Rtorch_C_torch_scalar_pow`, scalar, exponent)
}

C_torch_remainder <- function(self, other) {
    .Call(`_Rtorch_C_torch_remainder`, self, other)
}

C_torch_remainder_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_remainder_scalar`, self, scalar)
}

C_torch_floor_divide <- function(self, other) {
    .Call(`_Rtorch_C_torch_floor_divide`, self, other)
}

C_torch_floor_divide_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_floor_divide_scalar`, self, scalar)
}

C_torch_eq <- function(self, other) {
    .Call(`_Rtorch_C_torch_eq`, self, other)
}

C_torch_eq_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_eq_scalar`, self, scalar)
}

C_torch_ne <- function(self, other) {
    .Call(`_Rtorch_C_torch_ne`, self, other)
}

C_torch_ne_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_ne_scalar`, self, scalar)
}

C_torch_lt <- function(self, other) {
    .Call(`_Rtorch_C_torch_lt`, self, other)
}

C_torch_lt_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_lt_scalar`, self, scalar)
}

C_torch_le <- function(self, other) {
    .Call(`_Rtorch_C_torch_le`, self, other)
}

C_torch_le_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_le_scalar`, self, scalar)
}

C_torch_gt <- function(self, other) {
    .Call(`_Rtorch_C_torch_gt`, self, other)
}

C_torch_gt_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_gt_scalar`, self, scalar)
}

C_torch_ge <- function(self, other) {
    .Call(`_Rtorch_C_torch_ge`, self, other)
}

C_torch_ge_scalar <- function(self, scalar) {
    .Call(`_Rtorch_C_torch_ge_scalar`, self, scalar)
}

C_torch_bmm <- function(self, other) {
    .Call(`_Rtorch_C_torch_bmm`, self, other)
}

C_torch_transpose <- function(self, dim0_sexp, dim1_sexp) {
    .Call(`_Rtorch_C_torch_transpose`, self, dim0_sexp, dim1_sexp)
}

C_torch_flatten <- function(self, start_dim_sexp, end_dim_sexp) {
    .Call(`_Rtorch_C_torch_flatten`, self, start_dim_sexp, end_dim_sexp)
}

C_torch_clone <- function(self) {
    .Call(`_Rtorch_C_torch_clone`, self)
}

C_torch_contiguous <- function(self) {
    .Call(`_Rtorch_C_torch_contiguous`, self)
}

C_torch_to_dtype <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_to_dtype`, self, dtype_sexp)
}

C_torch_item <- function(self) {
    .Call(`_Rtorch_C_torch_item`, self)
}

C_torch_cat <- function(tensors_sexp, dim_sexp) {
    .Call(`_Rtorch_C_torch_cat`, tensors_sexp, dim_sexp)
}

C_torch_clamp <- function(self, min_sexp, max_sexp) {
    .Call(`_Rtorch_C_torch_clamp`, self, min_sexp, max_sexp)
}

C_torch_where <- function(condition, self, other) {
    .Call(`_Rtorch_C_torch_where`, condition, self, other)
}

C_torch_sort <- function(self, dim_sexp, descending_sexp) {
    .Call(`_Rtorch_C_torch_sort`, self, dim_sexp, descending_sexp)
}

C_torch_flip <- function(self, dims_sexp) {
    .Call(`_Rtorch_C_torch_flip`, self, dims_sexp)
}

C_torch_cumsum <- function(self, dim_sexp) {
    .Call(`_Rtorch_C_torch_cumsum`, self, dim_sexp)
}

C_torch_maximum <- function(self, other) {
    .Call(`_Rtorch_C_torch_maximum`, self, other)
}

C_torch_multinomial <- function(self, num_samples_sexp, replacement_sexp) {
    .Call(`_Rtorch_C_torch_multinomial`, self, num_samples_sexp, replacement_sexp)
}

C_torch_outer <- function(self, vec2) {
    .Call(`_Rtorch_C_torch_outer`, self, vec2)
}

C_torch_triu <- function(self, diagonal_sexp) {
    .Call(`_Rtorch_C_torch_triu`, self, diagonal_sexp)
}

C_torch_norm <- function(self, p_sexp, dim_sexp, keepdim_sexp) {
    .Call(`_Rtorch_C_torch_norm`, self, p_sexp, dim_sexp, keepdim_sexp)
}

C_torch_std <- function(self, dim_sexp, keepdim_sexp, correction_sexp) {
    .Call(`_Rtorch_C_torch_std`, self, dim_sexp, keepdim_sexp, correction_sexp)
}

C_torch_complex <- function(real, imag) {
    .Call(`_Rtorch_C_torch_complex`, real, imag)
}

C_torch_real <- function(self) {
    .Call(`_Rtorch_C_torch_real`, self)
}

C_torch_imag <- function(self) {
    .Call(`_Rtorch_C_torch_imag`, self)
}

C_torch_polar <- function(abs, angle) {
    .Call(`_Rtorch_C_torch_polar`, abs, angle)
}

C_torch_view_as_real <- function(self) {
    .Call(`_Rtorch_C_torch_view_as_real`, self)
}

C_torch_stft <- function(input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, return_complex_sexp) {
    .Call(`_Rtorch_C_torch_stft`, input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, return_complex_sexp)
}

C_torch_istft <- function(input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, length_sexp, return_complex_sexp) {
    .Call(`_Rtorch_C_torch_istft`, input, n_fft_sexp, hop_sexp, win_length_sexp, window, center_sexp, normalized_sexp, onesided_sexp, length_sexp, return_complex_sexp)
}

C_torch_hann_window <- function(length_sexp, periodic_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_hann_window`, length_sexp, periodic_sexp, dtype_sexp, device_sexp)
}

C_torch_tensor <- function(data, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_tensor`, data, dtype_sexp, device_sexp)
}

C_torch_tensor_raw <- function(data, dim_sexp, dtype_sexp) {
    .Call(`_Rtorch_C_torch_tensor_raw`, data, dim_sexp, dtype_sexp)
}

C_torch_zeros <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_zeros`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_ones <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_ones`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_randn <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_randn`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_empty_like <- function(self) {
    .Call(`_Rtorch_C_torch_empty_like`, self)
}

C_torch_empty <- function(size_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_empty`, size_sexp, dtype_sexp, device_sexp)
}

C_torch_tensor_from_buffer <- function(raw_sexp, shape_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_tensor_from_buffer`, raw_sexp, shape_sexp, dtype_sexp, device_sexp)
}

C_torch_arange <- function(start_sexp, end_sexp, step_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_arange`, start_sexp, end_sexp, step_sexp, dtype_sexp, device_sexp)
}

C_torch_full <- function(size_sexp, fill_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_full`, size_sexp, fill_sexp, dtype_sexp, device_sexp)
}

C_torch_linspace <- function(start_sexp, end_sexp, steps_sexp, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_torch_linspace`, start_sexp, end_sexp, steps_sexp, dtype_sexp, device_sexp)
}

C_torch_ones_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_ones_like`, self, dtype_sexp)
}

C_torch_zeros_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_zeros_like`, self, dtype_sexp)
}

C_torch_randn_like <- function(self, dtype_sexp) {
    .Call(`_Rtorch_C_torch_randn_like`, self, dtype_sexp)
}

C_torch_permute <- function(self, dims_sexp) {
    .Call(`_Rtorch_C_torch_permute`, self, dims_sexp)
}

C_torch_expand <- function(self, size_sexp) {
    .Call(`_Rtorch_C_torch_expand`, self, size_sexp)
}

C_torch_gather <- function(self, dim_sexp, index) {
    .Call(`_Rtorch_C_torch_gather`, self, dim_sexp, index)
}

C_torch_masked_fill <- function(self, mask, value_sexp) {
    .Call(`_Rtorch_C_torch_masked_fill`, self, mask, value_sexp)
}

C_torch_masked_fill_ <- function(self, mask, value_sexp) {
    .Call(`_Rtorch_C_torch_masked_fill_`, self, mask, value_sexp)
}

C_torch_copy_ <- function(self, src) {
    .Call(`_Rtorch_C_torch_copy_`, self, src)
}

C_torch_normal_ <- function(self, mean_sexp, std_sexp) {
    .Call(`_Rtorch_C_torch_normal_`, self, mean_sexp, std_sexp)
}

C_torch_uniform_ <- function(self, from_sexp, to_sexp) {
    .Call(`_Rtorch_C_torch_uniform_`, self, from_sexp, to_sexp)
}

C_torch_zero_ <- function(self) {
    .Call(`_Rtorch_C_torch_zero_`, self)
}

C_torch_fill_ <- function(self, value_sexp) {
    .Call(`_Rtorch_C_torch_fill_`, self, value_sexp)
}

C_torch_repeat <- function(self, sizes_sexp) {
    .Call(`_Rtorch_C_torch_repeat`, self, sizes_sexp)
}

C_torch_repeat_interleave <- function(self, repeats_sexp, dim_sexp) {
    .Call(`_Rtorch_C_torch_repeat_interleave`, self, repeats_sexp, dim_sexp)
}

C_torch_index_select <- function(self, dim_sexp, index) {
    .Call(`_Rtorch_C_torch_index_select`, self, dim_sexp, index)
}

C_torch_narrow <- function(self, dim_sexp, start_sexp, length_sexp) {
    .Call(`_Rtorch_C_torch_narrow`, self, dim_sexp, start_sexp, length_sexp)
}

C_torch_scatter_ <- function(self, dim_sexp, index, src) {
    .Call(`_Rtorch_C_torch_scatter_`, self, dim_sexp, index, src)
}

C_tensor_to_device <- function(self, device_sexp) {
    .Call(`_Rtorch_C_tensor_to_device`, self, device_sexp)
}

C_tensor_to_dtype_device <- function(self, dtype_sexp, device_sexp) {
    .Call(`_Rtorch_C_tensor_to_dtype_device`, self, dtype_sexp, device_sexp)
}

C_cuda_is_available <- function() {
    .Call(`_Rtorch_C_cuda_is_available`)
}

C_cuda_device_count <- function() {
    .Call(`_Rtorch_C_cuda_device_count`)
}

C_cuda_empty_cache <- function() {
    .Call(`_Rtorch_C_cuda_empty_cache`)
}

C_cuda_mem_info <- function() {
    .Call(`_Rtorch_C_cuda_mem_info`)
}

C_cuda_memory_stats <- function() {
    .Call(`_Rtorch_C_cuda_memory_stats`)
}

C_transformer_decoder_layer_step <- function(x_sexp, weights_sexp, self_cache_k_sexp, self_cache_v_sexp, cross_cache_k_sexp, cross_cache_v_sexp, n_head_sexp) {
    .Call(`_Rtorch_C_transformer_decoder_layer_step`, x_sexp, weights_sexp, self_cache_k_sexp, self_cache_v_sexp, cross_cache_k_sexp, cross_cache_v_sexp, n_head_sexp)
}

C_transformer_encoder_layer <- function(x_sexp, weights_sexp, n_head_sexp) {
    .Call(`_Rtorch_C_transformer_encoder_layer`, x_sexp, weights_sexp, n_head_sexp)
}

