# Auto-generated by tools/codegen_compat.R -- DO NOT EDIT
# Source: torch R package at ~/torch/R
# Generated: 2026-04-10 19:54:31.307369

# ---- nnf_* functional wrappers ----

#' @export
nnf_affine_grid <- function(theta, size, align_corners = FALSE) {
    torch_affine_grid_generator(theta, size, align_corners)
}

#' @export
nnf_area_under_min_fpr_fnr <- function(input, target) {
    is_positive <- target == target$max()
    is_negative <- is_positive$bitwise_not()
    if (as.logical(torch_sum(is_positive) == 0) || as.logical(torch_sum(is_negative) == 0)) {
        return(torch_sum(input * 0))
    }
    fn_diff <- -1L * is_positive
    fp_diff <- is_negative$to(dtype = torch_long())
    fp_denom <- torch_sum(is_negative)
    fn_denom <- torch_sum(is_positive)
    sorted_pred_ids <- torch_argsort(input, dim = 1, descending = TRUE)$squeeze(-1)
    sorted_fp_cum <- fp_diff[sorted_pred_ids]$cumsum(dim = 1)/fp_denom
    sorted_fn_cum <- -fn_diff[sorted_pred_ids]$flip(1)$cumsum(dim = 1)$flip(1)/fn_denom
    sorted_thresh_gr <- -input[sorted_pred_ids]
    sorted_dedup <- sorted_thresh_gr$diff(dim = 1) != 0
    padding <- sorted_dedup$slice(dim = 1, 0, 1)
    sorted_fp_end <- torch_cat(c(sorted_dedup, padding))
    sorted_fn_end <- torch_cat(c(padding, sorted_dedup))
    uniq_thresh_gr <- sorted_thresh_gr[sorted_fp_end]
    uniq_fp_after <- sorted_fp_cum[sorted_fp_end]
    uniq_fn_before <- sorted_fn_cum[sorted_fn_end]
    min_FPR_FNR <- torch_minimum(uniq_fp_after[1:-2], uniq_fn_before[2:N])
    constant_range_gr <- uniq_thresh_gr$diff()
    torch_sum(min_FPR_FNR * constant_range_gr, dim = 1)
}

#' @export
nnf_contrib_sparsemax <- function(input, dim = -1) {
    if (!is_torch_tensor(input)) {
        value_error("Input should be a tensor and got '{class(input)}.")
    }
    dim <- as_1_based_dim(dim)
    ptr <- cpp_contrib_torch_sparsemax(input$ptr, dim)
    Tensor$new(ptr = ptr)
}

#' @export
nnf_fold <- function(input, output_size, kernel_size, dilation = 1, padding = 0, stride = 1) {
    torch_col2im(self = input, output_size = nn_util_pair(output_size), kernel_size = nn_util_pair(kernel_size), dilation = nn_util_pair(dilation), padding = nn_util_pair(padding), stride = nn_util_pair(stride))
}

#' @export
nnf_grid_sample <- function(input, grid, mode = c("bilinear", "nearest"), padding_mode = c("zeros", "border", "reflection"), align_corners = FALSE) {
    if (mode == "bilinear") {
        mode_enum <- 0
    }
    else if (mode == "nearest") {
        mode_enum <- 1
    }
    else {
        value_error("Unknown mode name '{mode}'. Supported modes are 'bilinear'", "and 'nearest'.")
    }
    if (padding_mode == "zeros") {
        padding_mode_enum <- 0
    }
    else if (padding_mode == "border") {
        padding_mode_enum <- 1
    }
    else if (padding_mode == "reflection") {
        padding_mode_enum <- 2
    }
    else {
        value_error("Unknown padding mode name '{padding_mode}'. Supported modes are", "'zeros', 'border' and 'reflection'.")
    }
    torch_grid_sampler(input = input, grid = grid, interpolation_mode = mode_enum, padding_mode = padding_mode_enum, align_corners = align_corners)
}

#' @export
nnf_gumbel_softmax <- function(logits, tau = 1, hard = FALSE, dim = -1) {
    gumbels <- -torch_empty_like(logits, memory_format = torch_contiguous_format())
    gumbels <- gumbels$exponential_()$log()
    gumbels <- (logits + gumbels)/tau
    y_soft <- gumbels$softmax(dim)
    if (hard) {
        index <- y_soft$max(dim, keepdim = TRUE)[[2]]
        y_hard <- torch_zeros_like(logits, memory_format = torch_contiguous_format())
        y_hard <- y_hard$scatter_(dim, index, 1)
        ret <- y_hard - y_soft$detach() + y_soft
    }
    else {
        ret <- y_soft
    }
    ret
}

#' @export
nnf_local_response_norm <- function(input, size, alpha = 1e-04, beta = 0.75, k = 1) {
    dim <- input$dim()
    div <- input$mul(input)$unsqueeze(1)
    if (dim == 3) {
        div <- nnf_pad(div, c(0, 0, as.integer(size/2), as.integer((size - 1)/2)))
        div <- nnf_avg_pool2d(div, c(size, 1), stride = 1)$squeeze(1)
    }
    else {
        sizes <- input$size()
        div <- div$view(c(sizes[1], 1, sizes[2], sizes[3], -1))
        div <- nnf_pad(div, c(0, 0, 0, 0, as.integer(size/2), as.integer((size - 1)/2)))
        div <- nnf_avg_pool3d(div, c(size, 1, 1), stride = 1)$squeeze(1)
        div <- div$view(sizes)
    }
    div <- div$mul(alpha)$add(k)$pow(beta)
    input/div
}

#' @export
nnf_lp_pool1d <- function(input, norm_type, kernel_size, stride = NULL, ceil_mode = FALSE) {
    if (!is.null(stride) || length(stride) == 0) {
        out <- nnf_avg_pool1d(input$pow(norm_type), kernel_size, stride, 0, ceil_mode)
    }
    else {
        out <- nnf_avg_pool1d(input$pow(norm_type), kernel_size, padding = 0, ceil_mode = ceil_mode)
    }
    (torch_sign(out) * nnf_relu(torch_abs(out)))$mul(kernel_size)$pow(1/norm_type)
}

#' @export
nnf_lp_pool2d <- function(input, norm_type, kernel_size, stride = NULL, ceil_mode = FALSE) {
    k <- nn_util_pair(kernel_size)
    if (!length(stride) == 0) {
        out <- nnf_avg_pool2d(input$pow(norm_type), kernel_size, stride, 0, ceil_mode)
    }
    else {
        out <- nnf_avg_pool2d(input$pow(norm_type), kernel_size, padding = 0, ceil_mode = ceil_mode)
    }
    (torch_sign(out) * nnf_relu(torch_abs(out)))$mul(k[[1]] * k[[2]])$pow(1/norm_type)
}

#' @export
nnf_max_unpool1d <- function(input, indices, kernel_size, stride = NULL, padding = 0, output_size = NULL) {
    if (is.null(stride) || length(stride) == 0) {
        stride <- kernel_size
    }
    output_size <- unpool_output_size(input, kernel_size, stride, padding, output_size)
    output_size <- c(output_size, 1)
    torch_max_unpool2d(input$unsqueeze(3), indices$unsqueeze(3), output_size)$squeeze(3)
}

#' @export
nnf_multi_head_attention_forward <- function(query, key, value, embed_dim_to_check, num_heads, in_proj_weight, in_proj_bias, bias_k, bias_v, add_zero_attn, dropout_p, out_proj_weight, out_proj_bias, training = TRUE, key_padding_mask = NULL, need_weights = TRUE, attn_mask = NULL, avg_weights = TRUE, use_separate_proj_weight = FALSE, q_proj_weight = NULL, k_proj_weight = NULL, v_proj_weight = NULL, static_k = NULL, static_v = NULL, batch_first = FALSE) {
    if (batch_first) {
        query <- torch_transpose(query, 1, 2)
        key <- torch_transpose(key, 1, 2)
        value <- torch_transpose(value, 1, 2)
    }
    o <- query$size()
    tgt_len <- o[[1]]
    bsz <- o[[2]]
    embed_dim <- o[[3]]
    head_dim <- floor(embed_dim/num_heads)
    scaling <- head_dim^(-0.5)
    if (!use_separate_proj_weight) {
        if (torch_equal(query, key) && torch_equal(key, value)) {
            o <- nnf_linear(query, in_proj_weight, in_proj_bias)$chunk(3, dim = -1)
            q <- o[[1]]
            k <- o[[2]]
            v <- o[[3]]
        }
        else if (torch_equal(key, value)) {
            b_ <- in_proj_bias
            start_ <- 1
            end_ <- embed_dim
            w_ <- in_proj_weight[start_:end_, ]
            if (!is.null(b_)) {
                b_ <- b_[start_:end_]
            }
            q <- nnf_linear(query, w_, b_)
            if (is.null(key)) {
                k <- NULL
                v <- NULL
            }
            else {
                b_ <- in_proj_bias
                start_ <- embed_dim + 1
                end_ <- NULL
                w_ <- in_proj_weight[start_:N, ]
                if (!is.null(b_)) {
                  b_ <- b_[start_:N]
                  o <- nnf_linear(key, w_, b_)$chunk(2, dim = -1)
                  k <- o[[1]]
                  v <- o[[2]]
                }
            }
        }
        else {
            b_ <- in_proj_bias
            start_ <- 1
            end_ <- embed_dim
            w_ <- in_proj_weight[start_:end_, ]
            if (!is.null(b_)) {
                b_ <- b_[start_:end_]
            }
            q <- nnf_linear(query, w_, b_)
            b_ <- in_proj_bias
            start_ <- embed_dim + 1
            end_ <- embed_dim * 2
            w_ <- in_proj_weight[start_:end_, ]
            if (!is.null(b_)) {
                b_ <- b_[start_:end_]
            }
            k <- nnf_linear(key, w_, b_)
            b_ <- in_proj_bias
            start_ <- embed_dim * 2 + 1
            end_ <- NULL
            w_ <- in_proj_weight[start_:N, ]
            if (!is.null(b_)) {
                b_ <- b_[start_:N]
            }
            v <- nnf_linear(value, w_, b_)
        }
    }
    else {
        if (!is.null(in_proj_bias)) {
            q <- nnf_linear(query, q_proj_weight, in_proj_bias[1:embed_dim])
            k <- nnf_linear(key, k_proj_weight, in_proj_bias[(embed_dim + 1):(embed_dim * 2)])
            v <- nnf_linear(value, v_proj_weight, in_proj_bias[(embed_dim * 2 + 1):N])
        }
        else {
            q <- nnf_linear(query, q_proj_weight, in_proj_bias)
            k <- nnf_linear(key, k_proj_weight, in_proj_bias)
            v <- nnf_linear(value, v_proj_weight, in_proj_bias)
        }
    }
    q <- q * scaling
    if (!is.null(bias_k) && !is.null(bias_v)) {
        if (is.null(static_k) && is.null(static_v)) {
            k <- torch_cat(list(k, bias_k[["repeat"]](c(1, bsz, 1))))
            v <- torch_cat(list(v, bias_v[["repeat"]](c(1, bsz, 1))))
            if (!is.null(attn_mask)) {
                attn_mask <- nnf_pad(attn_mask, c(0, 1))
            }
            if (!is.null(key_padding_mask)) {
                key_padding_mask <- nnf_pad(key_padding_mask, c(0, 1))
            }
        }
    }
    q <- q$contiguous()$view(c(tgt_len, bsz * num_heads, head_dim))$transpose(1, 2)
    if (!is.null(k)) {
        k <- k$contiguous()$view(c(-1, bsz * num_heads, head_dim))$transpose(1, 2)
    }
    if (!is.null(v)) {
        v <- v$contiguous()$view(c(-1, bsz * num_heads, head_dim))$transpose(1, 2)
    }
    if (!is.null(static_k)) {
        k <- static_k
    }
    if (!is.null(static_v)) {
        v <- static_v
    }
    src_len <- k$size(2)
    if (add_zero_attn) {
        src_len <- src_len + 1
        k_size <- k$size()
        k <- torch_cat(list(k, torch_zeros(append(list(k_size[1], 1), k_size[3:length(k_size)]), dtype = k$dtype, device = k$device)), dim = 2)
        v_size <- v$size()
        k <- torch_cat(list(k, torch_zeros(append(list(v_size[1], 1), v_size[3:length(v_size)]), dtype = v$dtype, device = v$device)), dim = 2)
        if (!is.null(attn_mask)) {
            attn_mask <- nnf_pad(attn_mask, list(0, 1))
        }
        if (!is.null(key_padding_mask)) {
            key_padding_mask <- nnf_pad(key_padding_mask, list(0, 1))
        }
    }
    attn_output_weights <- torch_bmm(q, k$transpose(2, 3))
    if (!is.null(attn_mask)) {
        if (attn_mask$dtype == torch_bool()) {
            attn_output_weights$masked_fill_(attn_mask, -Inf)
        }
        else {
            attn_output_weights <- attn_output_weights + attn_mask
        }
    }
    if (!is.null(key_padding_mask)) {
        attn_output_weights <- attn_output_weights$view(c(bsz, num_heads, tgt_len, src_len))
        if (key_padding_mask$dtype == torch_bool()) {
            attn_output_weights <- attn_output_weights$masked_fill(key_padding_mask$unsqueeze(2)$unsqueeze(3), -Inf)
        }
        else {
            attn_output_weights <- attn_output_weights + key_padding_mask$unsqueeze(2)$unsqueeze(3)
        }
        attn_output_weights <- attn_output_weights$view(c(bsz * num_heads, tgt_len, src_len))
    }
    attn_output_weights <- nnf_softmax(attn_output_weights, dim = -1)
    attn_output_weights <- nnf_dropout(attn_output_weights, p = dropout_p, training = training)
    attn_output <- torch_bmm(attn_output_weights, v)
    attn_output <- attn_output$transpose(1, 2)$contiguous()$view(c(tgt_len, bsz, embed_dim))
    attn_output <- nnf_linear(attn_output, out_proj_weight, out_proj_bias)
    if (batch_first) {
        attn_output <- torch_transpose(attn_output, 1, 2)
    }
    if (need_weights) {
        attn_output_weights <- attn_output_weights$view(c(bsz, num_heads, tgt_len, src_len))
        if (avg_weights) {
            return(list(attn_output, attn_output_weights$sum(dim = 2)/num_heads))
        }
        else {
            return(list(attn_output, attn_output_weights))
        }
    }
    else {
        return(list(attn_output, NULL))
    }
}

#' @export
nnf_multilabel_soft_margin_loss <- function(input, target, weight = NULL, reduction = "mean") {
    loss <- -(target * nnf_logsigmoid(input) + (1 - target) * nnf_logsigmoid(-input))
    if (!is.null(weight)) {
        loss <- loss * weight
    }
    class_dim <- input$dim() - 1
    C <- input$size(class_dim)
    loss <- loss$sum(dim = class_dim)/C
    if (reduction == "none") {
        ret <- loss
    }
    else if (reduction == "mean") {
        ret <- loss$mean()
    }
    else if (reduction == "sum") {
        ret <- loss$sum()
    }
    else {
        value_error("reduction is not valid.")
    }
    ret
}

#' @export
nnf_triplet_margin_with_distance_loss <- function(anchor, positive, negative, distance_function = NULL, margin = 1, swap = FALSE, reduction = "mean") {
    if (is.null(distance_function)) {
        distance_function <- nnf_pairwise_distance
    }
    positive_dist <- distance_function(anchor, positive)
    negative_dist <- distance_function(anchor, negative)
    if (swap) {
        swap_dist <- distance_function(positive, negative)
        negative_dist <- torch_min(negative_dist, swap_dist)
    }
    output <- torch_clamp(positive_dist - negative_dist + margin, min = 0)
    reduction_enum <- reduction_enum(reduction)
    if (reduction_enum == 1) {
        return(output$mean())
    }
    else if (reduction_enum == 2) {
        return(output$sum())
    }
    else {
        return(output)
    }
}

# ---- nn_* module constructors ----

#' @export
lp_pool_nd <- function(norm_type, kernel_size, stride = NULL, ceil_mode = FALSE) {
  nn_module("lp_pool_nd",
    initialize = function(norm_type, kernel_size, stride = NULL, ceil_mode = FALSE) {
        self$norm_type <- norm_type
        self$kernel_size <- kernel_size
        self$stride <- stride
        self$ceil_mode <- ceil_mode
    },
    forward = function()   stop("forward not defined")
  )(norm_type, kernel_size, stride, ceil_mode)
}

#' @export
nn_aum_loss <- function() {
  nn_module("nn_aum_loss",
    initialize = function() {
        super$initialize()
    },
    forward = function(input, target) {
        nnf_area_under_min_fpr_fnr(input, target)
    }
  )()
}

#' @export
nn_batch_norm_ <- function(num_features, eps = 1e-05, momentum = 0.1, affine = TRUE, track_running_stats = TRUE) {
  nn_module("nn_batch_norm_",
    initialize = function(num_features, eps = 1e-05, momentum = 0.1, affine = TRUE, track_running_stats = TRUE) {
        # parent init: num_features, eps, momentum, affine, track_running_stats
    },
    forward = function(input) {
        self$check_input_dim(input)
        if (is.null(self$momentum)) {
            exponential_average_factor <- 0
        }
        else {
            exponential_average_factor <- self$momentum
        }
        if (self$training && self$track_running_stats) {
            if (!is.null(self$num_batches_tracked)) {
                self$num_batches_tracked$add_(1L, 1L)
                if (is.null(self$momentum)) {
                    exponential_average_factor <- 1/self$num_batches_tracked
                }
                else {
                    exponential_average_factor <- self$momentum
                }
            }
        }
        if (self$training) {
            bn_training <- TRUE
        }
        else {
            bn_training <- is.null(self$running_mean) && is.null(self$running_var)
        }
        if (!self$training || self$track_running_stats) {
            running_mean <- self$running_mean
            running_var <- self$running_var
        }
        else {
            running_mean <- NULL
            running_var <- NULL
        }
        nnf_batch_norm(input, running_mean, running_var, self$weight, self$bias, bn_training, exponential_average_factor, self$eps)
    }
  )(num_features, eps, momentum, affine, track_running_stats)
}

#' @export
nn_bilinear <- function(in1_features, in2_features, out_features, bias = TRUE) {
  nn_module("nn_bilinear",
    initialize = function(in1_features, in2_features, out_features, bias = TRUE) {
        self$in1_features <- in1_features
        self$in2_features <- in2_features
        self$out_features <- out_features
        self$weight <- nn_parameter(torch_empty(out_features, in1_features, in2_features))
        if (bias) {
            self$bias <- nn_parameter(torch_empty(out_features))
        }
        else {
            self$bias <- NULL
        }
        self$reset_parameters()
    },
    forward = function(input1, input2) {
        nnf_bilinear(input1, input2, self$weight, self$bias)
    }
  )(in1_features, in2_features, out_features, bias)
}

#' @export
nn_contrib_sparsemax <- function(dim = -1) {
  nn_module("nn_contrib_sparsemax",
    initialize = function(dim = -1) {
        self$dim <- dim
    },
    forward = function(input) {
        nnf_contrib_sparsemax(input, self$dim)
    }
  )(dim)
}

#' @export
nn_conv_nd <- function(in_channels, out_channels, kernel_size, stride, padding, dilation, transposed, output_padding, groups, bias, padding_mode) {
  nn_module("nn_conv_nd",
    initialize = function(in_channels, out_channels, kernel_size, stride, padding, dilation, transposed, output_padding, groups, bias, padding_mode) {
        if (in_channels%%groups != 0) {
            value_error("`in_channels` must be divisible by groups")
        }
        if (out_channels%%groups != 0) {
            value_error("`out_channels` must be divisible by groups")
        }
        valid_padding_modes <- c("zeros", "reflect", "replicate", "circular")
        if (!padding_mode %in% valid_padding_modes) {
            value_error("padding_mode must be one of [{paste(valid_padding_modes, collapse = ', ')}],", "but got padding_mode='{padding_mode}'.")
        }
        self$in_channels <- in_channels
        self$out_channels <- out_channels
        self$kernel_size <- kernel_size
        self$stride <- stride
        self$padding <- padding
        self$dilation <- dilation
        self$transposed <- transposed
        self$output_padding <- output_padding
        self$groups <- groups
        self$padding_mode <- padding_mode
        self$reversed_padding_repeated_twice_ <- nn_util_reverse_repeat_tuple(self$padding, 2)
        if (transposed) {
            self$weight <- nn_parameter(torch_empty(in_channels, out_channels%/%groups, !!!kernel_size))
        }
        else {
            self$weight <- nn_parameter(torch_empty(out_channels, in_channels%/%groups, !!!kernel_size))
        }
        if (bias) {
            self$bias <- nn_parameter(torch_empty(out_channels))
        }
        else {
            self$register_parameter("bias", NULL)
        }
        self$reset_parameters()
    },
    forward = function()   stop("forward not defined")
  )(in_channels, out_channels, kernel_size, stride, padding, dilation, transposed, output_padding, groups, bias, padding_mode)
}

# SKIP: nn_conv_transpose_nd inherits from nn_conv_nd (hand-write)

#' @export
nn_dropout_nd <- function(p = 0.5, inplace = FALSE) {
  nn_module("nn_dropout_nd",
    initialize = function(p = 0.5, inplace = FALSE) {
        if (p < 0 || p > 1) {
            value_error("dropout probability has to be between 0 and 1 but got {p}")
        }
        self$p <- p
        self$inplace <- inplace
    },
    forward = function()   stop("forward not defined")
  )(p, inplace)
}

#' @export
nn_embedding_bag <- function(num_embeddings, embedding_dim, max_norm = NULL, norm_type = 2, scale_grad_by_freq = FALSE, mode = "mean", sparse = FALSE, include_last_offset = FALSE, padding_idx = NULL, .weight = NULL) {
  nn_module("nn_embedding_bag",
    initialize = function(num_embeddings, embedding_dim, max_norm = NULL, norm_type = 2, scale_grad_by_freq = FALSE, mode = "mean", sparse = FALSE, include_last_offset = FALSE, padding_idx = NULL, .weight = NULL) {
        self$num_embeddings <- num_embeddings
        self$embedding_dim <- embedding_dim
        if (!is.null(padding_idx)) {
            if (padding_idx > 0 && padding_idx > num_embeddings) {
                value_error("`padding_idx` must be within num_embeddings")
            }
            else if (padding_idx < 0) {
                if (padding_idx <= (-num_embeddings)) {
                    value_error("`padding_idx` must be within num_embeddings")
                }
                padding_idx <- self$num_embeddings + padding_idx
            }
        }
        self$padding_idx <- padding_idx
        self$max_norm <- max_norm
        self$norm_type <- norm_type
        self$scale_grad_by_freq <- scale_grad_by_freq
        if (is.null(.weight)) {
            self$weight <- nn_parameter(torch_empty(num_embeddings, embedding_dim))
            self$reset_parameters()
        }
        else {
            if (!all(.weight$size() == c(num_embeddings, embedding_dim))) {
                value_error("Shape of `.weight` does not match num_embeddings and embedding_dim")
            }
            self$weight <- nn_parameter(.weight)
        }
        self$mode = mode
        self$sparse = sparse
        self$include_last_offset = include_last_offset
    },
    forward = function(input, offsets = NULL, per_sample_weights = NULL) {
        nnf_embedding_bag(input, self$weight, offsets, self$max_norm, self$norm_type, self$scale_grad_by_freq, self$mode, self$sparse, per_sample_weights, self$include_last_offset, self$padding_idx)
    }
  )(num_embeddings, embedding_dim, max_norm, norm_type, scale_grad_by_freq, mode, sparse, include_last_offset, padding_idx, .weight)
}

#' @export
nn_fractional_max_pool2d <- function(kernel_size, output_size = NULL, output_ratio = NULL, return_indices = FALSE) {
  nn_module("nn_fractional_max_pool2d",
    initialize = function(kernel_size, output_size = NULL, output_ratio = NULL, return_indices = FALSE) {
        random_samples <- NULL
        self$kernel_size <- nn_util_pair(kernel_size)
        self$return_indices <- return_indices
        self$register_buffer("random_samples", random_samples)
        if (!is.null(output_size)) {
            output_size <- nn_util_pair(output_size)
        }
        self$output_size <- output_size
        if (!is.null(output_ratio)) {
            output_ratio <- nn_util_pair(output_ratio)
        }
        self$output_ratio <- output_ratio
        if (is.null(output_ratio) && is.null(output_size)) {
            value_error("both output_size and output_ratio are NULL")
        }
        if (!is.null(output_ratio) && !is.null(output_size)) {
            value_error("both output_size and output_ratio are not NULL")
        }
        if (!is.null(output_ratio)) {
            if (any(output_ratio > 1 | output_ratio < 0)) {
                value_error("output_ratio must be between 0 and 1.")
            }
        }
    },
    forward = function(input) {
        nnf_fractional_max_pool2d(input, self$kernel_size, self$output_size, self$output_ratio, self$return_indices, random_samples = self$random_samples)
    }
  )(kernel_size, output_size, output_ratio, return_indices)
}

#' @export
nn_fractional_max_pool3d <- function(kernel_size, output_size = NULL, output_ratio = NULL, return_indices = FALSE) {
  nn_module("nn_fractional_max_pool3d",
    initialize = function(kernel_size, output_size = NULL, output_ratio = NULL, return_indices = FALSE) {
        random_samples <- NULL
        self$kernel_size <- nn_util_triple(kernel_size)
        self$return_indices <- return_indices
        self$register_buffer("random_samples", random_samples)
        if (!is.null(output_size)) {
            output_size <- nn_util_triple(output_size)
        }
        self$output_size <- output_size
        if (!is.null(output_ratio)) {
            output_ratio <- nn_util_triple(output_ratio)
        }
        self$output_ratio <- output_ratio
        if (is.null(output_ratio) && is.null(output_size)) {
            value_error("both output_size and output_ratio are NULL")
        }
        if (!is.null(output_ratio) && !is.null(output_size)) {
            value_error("both output_size and output_ratio are not NULL")
        }
        if (!is.null(output_ratio)) {
            if (any(output_ratio > 1 | output_ratio < 0)) {
                value_error("output_ratio must be between 0 and 1.")
            }
        }
    },
    forward = function(input) {
        nnf_fractional_max_pool3d(input, self$kernel_size, self$output_size, self$output_ratio, self$return_indices, random_samples = self$random_samples)
    }
  )(kernel_size, output_size, output_ratio, return_indices)
}

# SKIP: nn_gru inherits from nn_rnn_base (hand-write)

#' @export
nn_loss <- function(reduction = "mean") {
  nn_module("nn_loss",
    initialize = function(reduction = "mean") {
        self$reduction <- reduction
    },
    forward = function()   stop("forward not defined")
  )(reduction)
}

#' @export
nn_lp_pool1d <- function() {
  nn_module("nn_lp_pool1d",
    initialize = function() { },
    forward = function(input) {
        nnf_lp_pool1d(input, self$norm_type, self$kernel_size, self$stride, self$ceil_mode)
    }
  )()
}

#' @export
nn_lp_pool2d <- function() {
  nn_module("nn_lp_pool2d",
    initialize = function() { },
    forward = function(input) {
        nnf_lp_pool2d(input, self$norm_type, self$kernel_size, self$stride, self$ceil_mode)
    }
  )()
}

#' @export
nn_max_pool_nd <- function(kernel_size, stride = NULL, padding = 0, dilation = 1, return_indices = FALSE, ceil_mode = FALSE) {
  nn_module("nn_max_pool_nd",
    initialize = function(kernel_size, stride = NULL, padding = 0, dilation = 1, return_indices = FALSE, ceil_mode = FALSE) {
        self$kernel_size <- kernel_size
        if (is.null(stride)) {
            self$stride <- kernel_size
        }
        else {
            self$stride <- stride
        }
        self$padding <- padding
        self$dilation <- dilation
        self$return_indices <- return_indices
        self$ceil_mode <- ceil_mode
    },
    forward = function()   stop("forward not defined")
  )(kernel_size, stride, padding, dilation, return_indices, ceil_mode)
}

#' @export
nn_max_unpool1d <- function(kernel_size, stride = NULL, padding = 0) {
  nn_module("nn_max_unpool1d",
    initialize = function(kernel_size, stride = NULL, padding = 0) {
        self$kernel_size <- nn_util_single(kernel_size)
        if (is.null(stride)) {
            stride <- kernel_size
        }
        self$stride <- nn_util_single(stride)
        self$padding <- nn_util_single(padding)
    },
    forward = function(input, indices, output_size = NULL) {
        nnf_max_unpool1d(input, indices, self$kernel_size, self$stride, self$padding, output_size)
    }
  )(kernel_size, stride, padding)
}

#' @export
nn_max_unpool2d <- function(kernel_size, stride = NULL, padding = 0) {
  nn_module("nn_max_unpool2d",
    initialize = function(kernel_size, stride = NULL, padding = 0) {
        self$kernel_size <- nn_util_pair(kernel_size)
        if (is.null(stride)) {
            stride <- kernel_size
        }
        self$stride <- nn_util_pair(stride)
        self$padding <- nn_util_pair(padding)
    },
    forward = function(input, indices, output_size = NULL) {
        nnf_max_unpool2d(input, indices, self$kernel_size, self$stride, self$padding, output_size)
    }
  )(kernel_size, stride, padding)
}

#' @export
nn_max_unpool3d <- function(kernel_size, stride = NULL, padding = 0) {
  nn_module("nn_max_unpool3d",
    initialize = function(kernel_size, stride = NULL, padding = 0) {
        self$kernel_size <- nn_util_triple(kernel_size)
        if (is.null(stride)) {
            stride <- kernel_size
        }
        self$stride <- nn_util_triple(stride)
        self$padding <- nn_util_triple(padding)
    },
    forward = function(input, indices, output_size = NULL) {
        nnf_max_unpool3d(input, indices, self$kernel_size, self$stride, self$padding, output_size)
    }
  )(kernel_size, stride, padding)
}

#' @export
nn_multihead_attention <- function(embed_dim, num_heads, dropout = 0, bias = TRUE, add_bias_kv = FALSE, add_zero_attn = FALSE, kdim = NULL, vdim = NULL, batch_first = FALSE) {
  nn_module("nn_multihead_attention",
    initialize = function(embed_dim, num_heads, dropout = 0, bias = TRUE, add_bias_kv = FALSE, add_zero_attn = FALSE, kdim = NULL, vdim = NULL, batch_first = FALSE) {
        self$embed_dim <- embed_dim
        if (!is.null(kdim)) {
            self$kdim <- kdim
        }
        else {
            self$kdim <- embed_dim
        }
        if (!is.null(vdim)) {
            self$vdim <- vdim
        }
        else {
            self$vdim <- embed_dim
        }
        self$qkv_same_embed_dim_ <- self$kdim == embed_dim && self$vdim == embed_dim
        self$num_heads <- num_heads
        self$dropout <- dropout
        self$head_dim <- embed_dim%/%num_heads
        if ((self$head_dim * num_heads) != self$embed_dim) {
            value_error("embed_dim must be divisible by num_heads")
        }
        if (!self$qkv_same_embed_dim_) {
            self$q_proj_weight <- nn_parameter(torch_empty(embed_dim, embed_dim))
            self$k_proj_weight <- nn_parameter(torch_empty(embed_dim, self$kdim))
            self$v_proj_weight <- nn_parameter(torch_empty(embed_dim, self$vdim))
            self$register_parameter("in_proj_weight", NULL)
        }
        else {
            self$in_proj_weight <- nn_parameter(torch_empty(3 * embed_dim, embed_dim))
            self$register_parameter("q_proj_weight", NULL)
            self$register_parameter("k_proj_weight", NULL)
            self$register_parameter("v_proj_weight", NULL)
        }
        if (bias) {
            self$in_proj_bias <- nn_parameter(torch_empty(3 * embed_dim))
        }
        else {
            self$register_parameter("in_proj_bias", NULL)
        }
        self$out_proj <- nn_linear(embed_dim, embed_dim, bias = bias)
        if (add_bias_kv) {
            self$bias_k <- nn_parameter(torch_empty(1, 1, embed_dim))
            self$bias_v <- nn_parameter(torch_empty(1, 1, embed_dim))
        }
        else {
            self$bias_k <- NULL
            self$bias_v <- NULL
        }
        self$add_zero_attn <- add_zero_attn
        self$batch_first <- batch_first
        self$reset_parameters()
    },
    forward = function(query, key, value, key_padding_mask = NULL, need_weights = TRUE, attn_mask = NULL, avg_weights = TRUE) {
        if (!self$qkv_same_embed_dim_) {
            nnf_multi_head_attention_forward(query, key, value, self$embed_dim, self$num_heads, self$in_proj_weight, self$in_proj_bias, self$bias_k, self$bias_v, self$add_zero_attn, self$dropout, self$out_proj$weight, self$out_proj$bias, training = self$training, key_padding_mask = key_padding_mask, need_weights = need_weights, attn_mask = attn_mask, use_separate_proj_weight = TRUE, q_proj_weight = self$q_proj_weight, k_proj_weight = self$k_proj_weight, v_proj_weight = self$v_proj_weight, batch_first = self$batch_first)
        }
        else {
            nnf_multi_head_attention_forward(query, key, value, self$embed_dim, self$num_heads, self$in_proj_weight, self$in_proj_bias, self$bias_k, self$bias_v, self$add_zero_attn, self$dropout, self$out_proj$weight, self$out_proj$bias, training = self$training, key_padding_mask = key_padding_mask, need_weights = need_weights, attn_mask = attn_mask, avg_weights = avg_weights, batch_first = self$batch_first)
        }
    }
  )(embed_dim, num_heads, dropout, bias, add_bias_kv, add_zero_attn, kdim, vdim, batch_first)
}

#' @export
nn_multilabel_soft_margin_loss <- function(weight = NULL, reduction = "mean") {
  nn_module("nn_multilabel_soft_margin_loss",
    initialize = function(weight = NULL, reduction = "mean") {
        # parent init: weight = weight, reduction = reduction
    },
    forward = function(input, target) {
        nnf_multilabel_soft_margin_loss(input, target, weight = self$weight, reduction = self$reduction)
    }
  )(weight, reduction)
}

#' @export
nn_norm_base_ <- function(num_features, eps = 1e-05, momentum = 0.1, affine = TRUE, track_running_stats = TRUE) {
  nn_module("nn_norm_base_",
    initialize = function(num_features, eps = 1e-05, momentum = 0.1, affine = TRUE, track_running_stats = TRUE) {
        self$num_features <- num_features
        self$eps <- eps
        self$momentum <- momentum
        self$affine <- affine
        self$track_running_stats <- track_running_stats
        if (self$affine) {
            self$weight <- nn_parameter(torch_empty(num_features))
            self$bias <- nn_parameter(torch_empty(num_features))
        }
        else {
            self$weight <- NULL
            self$bias <- NULL
        }
        if (self$track_running_stats) {
            self$running_mean <- nn_buffer(torch_zeros(num_features))
            self$running_var <- nn_buffer(torch_ones(num_features))
            self$num_batches_tracked <- nn_buffer(torch_tensor(0, dtype = torch_long()))
        }
        else {
            self$running_mean <- NULL
            self$running_var <- NULL
            self$num_batches_tracked <- NULL
        }
        self$reset_parameters()
    },
    forward = function()   stop("forward not defined")
  )(num_features, eps, momentum, affine, track_running_stats)
}

# SKIP: nn_rnn inherits from nn_rnn_base (hand-write)

#' @export
nn_rnn_base <- function(mode, input_size, hidden_size, num_layers = 1, bias = TRUE, batch_first = FALSE, dropout = 0, bidirectional = FALSE) {
  nn_module("nn_rnn_base",
    initialize = function(mode, input_size, hidden_size, num_layers = 1, bias = TRUE, batch_first = FALSE, dropout = 0, bidirectional = FALSE) {
        self$mode <- mode
        self$input_size <- input_size
        self$hidden_size <- hidden_size
        self$num_layers <- num_layers
        self$bias <- bias
        self$batch_first <- batch_first
        self$dropout <- dropout
        self$bidirectional <- bidirectional
        self$proj_size <- 0
        if (bidirectional) {
            num_directions <- 2
        }
        else {
            num_directions <- 1
        }
        if (dropout > 0 && num_layers == 1) {
            warn("dropout option adds dropout after all but last ", "recurrent layer, so non-zero dropout expects ", "num_layers greater than 1, but got dropout={dropout} and ", "num_layers={num_layers}")
        }
        if (mode == "LSTM") {
            gate_size <- 4 * hidden_size
        }
        else if (mode == "GRU") {
            gate_size <- 3 * hidden_size
        }
        else if (mode == "RNN_TANH") {
            gate_size <- hidden_size
        }
        else if (mode == "RNN_RELU") {
            gate_size <- hidden_size
        }
        else {
            value_error("Unrecognized RNN mode: {mode}")
        }
        self$flat_weights_names_ <- list()
        self$all_weights_ <- list()
        for (layer in seq_len(num_layers)) {
            for (direction in seq_len(num_directions)) {
                if (layer == 1) {
                    layer_input_size <- input_size
                }
                else {
                    layer_input_size <- hidden_size * num_directions
                }
                w_ih <- nn_parameter(torch_empty(gate_size, layer_input_size))
                w_hh <- nn_parameter(torch_empty(gate_size, hidden_size))
                b_ih <- nn_parameter(torch_empty(gate_size))
                b_hh <- nn_parameter(torch_empty(gate_size))
                layer_params <- list(w_ih, w_hh, b_ih, b_hh)
                if (direction == 2) {
                    suffix <- "_reverse"
                }
                else {
                    suffix <- ""
                }
                param_names <- c(glue::glue("weight_ih_l{layer}{suffix}"), glue::glue("weight_hh_l{layer}{suffix}"))
                if (bias) {
                    param_names <- c(param_names, c(glue::glue("bias_ih_l{layer}{suffix}"), glue::glue("bias_hh_l{layer}{suffix}")))
                }
                for (i in seq_along(param_names)) {
                    self[[param_names[i]]] <- layer_params[[i]]
                }
                self$flat_weight_names_ <- c(self$flat_weight_names_, param_names)
                self$all_weights_ <- c(self$all_weights_, param_names)
            }
        }
        self$flat_weights_ <- lapply(self$flat_weight_names_, function(wn) {
            self[[wn]]
        })
        self$flatten_parameters()
        self$reset_parameters()
    },
    forward = function(input, hx = NULL) {
        is_packed <- is_packed_sequence(input)
        if (is_packed) {
            batch_sizes <- input$batch_sizes
            sorted_indices <- input$sorted_indices
            unsorted_indices <- input$unsorted_indices
            max_batch_size <- as_array(batch_sizes[1]$to(dtype = torch_int()))
            input <- input$data
        }
        else {
            batch_sizes <- NULL
            if (self$batch_first) {
                max_batch_size <- input$size(1)
            }
            else {
                max_batch_size <- input$size(2)
            }
            sorted_indices <- NULL
            unsorted_indices <- NULL
        }
        if (is.null(hx)) {
            num_directions <- ifelse(self$bidirectional, 2, 1)
            hx <- torch_zeros(self$num_layers * num_directions, max_batch_size, self$hidden_size, dtype = input$dtype, device = input$device)
            if (self$mode == "LSTM") {
                hx <- list(hx, hx)
            }
        }
        else {
            hx <- self$permute_hidden(hx, sorted_indices)
        }
        impl_ <- rnn_impls_[[self$mode]]
        if (is.null(batch_sizes)) {
            result <- impl_(input = input, hx = hx, params = self$flat_weights_, has_biases = self$bias, num_layers = self$num_layers, dropout = self$dropout, train = self$training, bidirectional = self$bidirectional, batch_first = self$batch_first)
        }
        else {
            result <- impl_(data = input, hx = hx, batch_sizes = batch_sizes, params = self$flat_weights_, has_biases = self$bias, num_layers = self$num_layers, dropout = self$dropout, train = self$training, bidirectional = self$bidirectional)
        }
        output <- result[[1]]
        hidden <- result[-1]
        if (length(hidden) == 1) {
            hidden <- hidden[[1]]
        }
        if (is_packed) {
            output <- new_packed_sequence(output, batch_sizes, sorted_indices, unsorted_indices)
        }
        list(output, self$permute_hidden(hidden, unsorted_indices))
    }
  )(mode, input_size, hidden_size, num_layers, bias, batch_first, dropout, bidirectional)
}

#' @export
nn_transformer_encoder <- function(encoder_layer, num_layers, norm = NULL) {
  nn_module("nn_transformer_encoder",
    initialize = function(encoder_layer, num_layers, norm = NULL) {
        if (!is_nn_module(encoder_layer)) {
            value_error("`encoder_layer` must be an `nn_module` (transformer encoder layer instance).")
        }
        self$num_layers <- num_layers
        self$layers <- nn_module_list(lapply(seq_len(num_layers), function(i) {
            clone_module(encoder_layer, deep = TRUE)
        }))
        self$norm <- norm
    },
    forward = function(src, mask = NULL, src_key_padding_mask = NULL, is_causal = FALSE) {
        output <- src
        for (i in seq_along(self$layers)) {
            output <- self$layers[[i]](output, src_mask = mask, src_key_padding_mask = src_key_padding_mask, is_causal = is_causal)
        }
        if (!is.null(self$norm)) {
            output <- self$norm(output)
        }
        return(output)
    }
  )(encoder_layer, num_layers, norm)
}

#' @export
nn_transformer_encoder_layer <- function(d_model, nhead, dim_feedforward = 2048, dropout = 0.1, activation = "relu", layer_norm_eps = 1e-05, batch_first = FALSE, norm_first = FALSE, bias = TRUE) {
  nn_module("nn_transformer_encoder_layer",
    initialize = function(d_model, nhead, dim_feedforward = 2048, dropout = 0.1, activation = "relu", layer_norm_eps = 1e-05, batch_first = FALSE, norm_first = FALSE, bias = TRUE) {
        self$norm_first <- norm_first
        self$self_attn <- nn_multihead_attention(embed_dim = d_model, num_heads = nhead, dropout = dropout, bias = bias, batch_first = batch_first)
        self$linear1 <- nn_linear(d_model, dim_feedforward, bias = bias)
        self$linear2 <- nn_linear(dim_feedforward, d_model, bias = bias)
        self$dropout <- nn_dropout(dropout)
        self$dropout1 <- nn_dropout(dropout)
        self$dropout2 <- nn_dropout(dropout)
        self$norm1 <- nn_layer_norm(normalized_shape = d_model, eps = layer_norm_eps, elementwise_affine = bias)
        self$norm2 <- nn_layer_norm(normalized_shape = d_model, eps = layer_norm_eps, elementwise_affine = bias)
        if (is.character(activation)) {
            act_name <- tolower(activation)
            if (act_name == "relu") {
                self$activation <- function(x) nnf_relu(x)
                self$activation_relu_or_gelu <- 1
            }
            else if (act_name == "gelu") {
                self$activation <- function(x) nnf_gelu(x)
                self$activation_relu_or_gelu <- 2
            }
            else {
                value_error("Unsupported activation string: {activation}. Use 'relu', 'gelu', or a callable function.")
            }
        }
        else if (is.function(activation)) {
            self$activation <- activation
            self$activation_relu_or_gelu <- 0
        }
        else {
            value_error("activation must be a string ('relu' or 'gelu') or a function.")
        }
    },
    forward = function(src, src_mask = NULL, src_key_padding_mask = NULL, is_causal = FALSE) {
        if (!is.null(src_mask) && is_causal) {
            value_error("Explicit src_mask should not be set when is_causal=TRUE. Use one or the other.")
        }
        attn_mask_eff <- src_mask
        if (is_causal) {
            if (self$self_attn$batch_first) {
                L <- dim(src)[2]
            }
            else {
                L <- dim(src)[1]
            }
            attn_mask_eff <- torch_ones(c(L, L), dtype = torch_bool())
            attn_mask_eff <- attn_mask_eff$triu(diagonal = 1)
        }
        if (self$norm_first) {
            norm_src <- self$norm1(src)
            attn_out <- self$self_attn(norm_src, norm_src, norm_src, attn_mask = attn_mask_eff, key_padding_mask = src_key_padding_mask, need_weights = FALSE)[[1]]
            src2 <- src + self$dropout1(attn_out)
            norm_src2 <- self$norm2(src2)
            ff_out <- self$linear2(self$dropout(self$activation(self$linear1(norm_src2))))
            out <- src2 + self$dropout2(ff_out)
        }
        else {
            attn_out <- self$self_attn(src, src, src, attn_mask = attn_mask_eff, key_padding_mask = src_key_padding_mask, need_weights = FALSE)[[1]]
            src2 <- src + self$dropout1(attn_out)
            out1 <- self$norm1(src2)
            ff_out <- self$linear2(self$dropout(self$activation(self$linear1(out1))))
            out2 <- out1 + self$dropout2(ff_out)
            out <- self$norm2(out2)
        }
        return(out)
    }
  )(d_model, nhead, dim_feedforward, dropout, activation, layer_norm_eps, batch_first, norm_first, bias)
}

#' @export
nn_triplet_margin_with_distance_loss <- function(distance_function = NULL, margin = 1, swap = FALSE, reduction = "mean") {
  nn_module("nn_triplet_margin_with_distance_loss",
    initialize = function(distance_function = NULL, margin = 1, swap = FALSE, reduction = "mean") {
        # parent init: reduction = reduction
        if (is.null(distance_function)) {
            self$distance_function <- nn_pairwise_distance()
        }
        else {
            self$distance_function <- distance_function
        }
        self$margin <- margin
        self$swap <- swap
    },
    forward = function(anchor, positive, negative) {
        nnf_triplet_margin_with_distance_loss(anchor, positive, negative, distance_function = self$distance_function, margin = self$margin, swap = self$swap, reduction = self$reduction)
    }
  )(distance_function, margin, swap, reduction)
}

#' @export
nn_weighted_loss <- function(weight = NULL, reduction = "mean") {
  nn_module("nn_weighted_loss",
    initialize = function(weight = NULL, reduction = "mean") {
        # parent init: reduction
        if (!is.null(weight) && !inherits(weight, "torch_tensor")) {
            weight = torch_tensor(weight)
        }
        self$register_buffer("weight", weight)
    },
    forward = function()   stop("forward not defined")
  )(weight, reduction)
}

