# Auto-generated by tools/codegen.R -- DO NOT EDIT
# Source: native_functions.yaml

# ---- Namespace functions ----


#' @export
torch_absolute <- function(self) {
    C_torch_absolute(self)
}

#' @export
torch_angle <- function(self) {
    C_torch_angle(self)
}

#' @export
torch_view_as_complex <- function(self) {
    C_torch_view_as_complex(self)
}

#' @export
torch_sgn <- function(self) {
    C_torch_sgn(self)
}

#' @export
torch_acos <- function(self) {
    C_torch_acos(self)
}

#' @export
torch_arccos <- function(self) {
    C_torch_arccos(self)
}

#' @export
torch_all <- function(self, dim, keepdim = FALSE) {
    C_torch_all(self, as.integer(dim), as.logical(keepdim))
}

#' @export
torch_any <- function(self, dim, keepdim = FALSE) {
    C_torch_any(self, as.integer(dim), as.logical(keepdim))
}

#' @export
torch_acosh <- function(self) {
    C_torch_acosh(self)
}

#' @export
torch_arccosh <- function(self) {
    C_torch_arccosh(self)
}

#' @export
torch_asinh <- function(self) {
    C_torch_asinh(self)
}

#' @export
torch_arcsinh <- function(self) {
    C_torch_arcsinh(self)
}

#' @export
torch_atanh <- function(self) {
    C_torch_atanh(self)
}

#' @export
torch_arctanh <- function(self) {
    C_torch_arctanh(self)
}

#' @export
torch_asin <- function(self) {
    C_torch_asin(self)
}

#' @export
torch_arcsin <- function(self) {
    C_torch_arcsin(self)
}

#' @export
torch_atan <- function(self) {
    C_torch_atan(self)
}

#' @export
torch_arctan <- function(self) {
    C_torch_arctan(self)
}

#' @export
torch_atleast_1d <- function(self) {
    C_torch_atleast_1d(self)
}

#' @export
torch_atleast_2d <- function(self) {
    C_torch_atleast_2d(self)
}

#' @export
torch_atleast_3d <- function(self) {
    C_torch_atleast_3d(self)
}

#' @export
torch_bitwise_not <- function(self) {
    C_torch_bitwise_not(self)
}

#' @export
torch_copysign <- function(self, other) {
    C_torch_copysign(self, other)
}

#' @export
torch_logical_xor <- function(self, other) {
    C_torch_logical_xor(self, other)
}

#' @export
torch_logical_and <- function(self, other) {
    C_torch_logical_and(self, other)
}

#' @export
torch_logical_or <- function(self, other) {
    C_torch_logical_or(self, other)
}

#' @export
torch_clamp_max <- function(self, max) {
    C_torch_clamp_max(self, max)
}

#' @export
torch_clamp_min <- function(self, min) {
    C_torch_clamp_min(self, min)
}

#' @export
torch_cosh <- function(self) {
    C_torch_cosh(self)
}

#' @export
torch_corrcoef <- function(self) {
    C_torch_corrcoef(self)
}

#' @export
torch_diag_embed <- function(self, offset = 0, dim1 = -2, dim2 = -1) {
    C_torch_diag_embed(self, as.integer(offset), as.integer(dim1), as.integer(dim2))
}

#' @export
torch_diagflat <- function(self, offset = 0) {
    C_torch_diagflat(self, as.integer(offset))
}

#' @export
torch_diagonal <- function(self, offset = 0, dim1 = 0, dim2 = 1) {
    C_torch_diagonal(self, as.integer(offset), as.integer(dim1), as.integer(dim2))
}

#' @export
torch_linalg_diagonal <- function(A, offset = 0, dim1 = -2, dim2 = -1) {
    C_torch_linalg_diagonal(A, as.integer(offset), as.integer(dim1), as.integer(dim2))
}

#' @export
torch_divide <- function(self, other) {
    C_torch_divide(self, other)
}

#' @export
torch_true_divide <- function(self, other) {
    C_torch_true_divide(self, other)
}

#' @export
torch_dot <- function(self, tensor) {
    C_torch_dot(self, tensor)
}

#' @export
torch_vdot <- function(self, other) {
    C_torch_vdot(self, other)
}

#' @export
torch_erf <- function(self) {
    C_torch_erf(self)
}

#' @export
torch_erfc <- function(self) {
    C_torch_erfc(self)
}

#' @export
torch_exp2 <- function(self) {
    C_torch_exp2(self)
}

#' @export
torch_expm1 <- function(self) {
    C_torch_expm1(self)
}

#' @export
torch_fill <- function(self, value) {
    C_torch_fill(self, value)
}

#' @export
torch_frac <- function(self) {
    C_torch_frac(self)
}

#' @export
torch_gcd <- function(self, other) {
    C_torch_gcd(self, other)
}

#' @export
torch_lcm <- function(self, other) {
    C_torch_lcm(self, other)
}

#' @export
torch_isnan <- function(self) {
    C_torch_isnan(self)
}

#' @export
torch_isreal <- function(self) {
    C_torch_isreal(self)
}

#' @export
torch_kron <- function(self, other) {
    C_torch_kron(self, other)
}

#' @export
torch_log1p <- function(self) {
    C_torch_log1p(self)
}

#' @export
torch_logaddexp <- function(self, other) {
    C_torch_logaddexp(self, other)
}

#' @export
torch_logaddexp2 <- function(self, other) {
    C_torch_logaddexp2(self, other)
}

#' @export
torch_xlogy <- function(self, other) {
    C_torch_xlogy(self, other)
}

#' @export
torch_logcumsumexp <- function(self, dim) {
    C_torch_logcumsumexp(self, as.integer(dim))
}

#' @export
torch_matrix_power <- function(self, n) {
    C_torch_matrix_power(self, as.integer(n))
}

#' @export
torch_matrix_exp <- function(self) {
    C_torch_matrix_exp(self)
}

#' @export
torch_median <- function(self) {
    C_torch_median(self)
}

#' @export
torch_nanmedian <- function(self) {
    C_torch_nanmedian(self)
}

#' @export
torch_multiply <- function(self, other) {
    C_torch_multiply(self, other)
}

#' @export
torch_mv <- function(self, vec) {
    C_torch_mv(self, vec)
}

#' @export
torch_mvlgamma <- function(self, p) {
    C_torch_mvlgamma(self, as.integer(p))
}

#' @export
torch_pdist <- function(self, p = 2) {
    C_torch_pdist(self, as.double(p))
}

#' @export
torch_movedim <- function(self, source, destination) {
    C_torch_movedim(self, as.integer(source), as.integer(destination))
}

#' @export
torch_moveaxis <- function(self, source, destination) {
    C_torch_moveaxis(self, as.integer(source), as.integer(destination))
}

#' @export
torch_adjoint <- function(self) {
    C_torch_adjoint(self)
}

#' @export
torch_pixel_shuffle <- function(self, upscale_factor) {
    C_torch_pixel_shuffle(self, as.integer(upscale_factor))
}

#' @export
torch_pixel_unshuffle <- function(self, downscale_factor) {
    C_torch_pixel_unshuffle(self, as.integer(downscale_factor))
}

#' @export
torch_pinverse <- function(self, rcond = 1e-15) {
    C_torch_pinverse(self, as.double(rcond))
}

#' @export
torch_rad2deg <- function(self) {
    C_torch_rad2deg(self)
}

#' @export
torch_deg2rad <- function(self) {
    C_torch_deg2rad(self)
}

#' @export
torch_ravel <- function(self) {
    C_torch_ravel(self)
}

#' @export
torch_reciprocal <- function(self) {
    C_torch_reciprocal(self)
}

#' @export
torch_negative <- function(self) {
    C_torch_negative(self)
}

#' @export
torch_relu6 <- function(self) {
    C_torch_relu6(self)
}

#' @export
torch_prelu <- function(self, weight) {
    C_torch_prelu(self, weight)
}

#' @export
torch_hardshrink <- function(self, lambd = 0.5) {
    C_torch_hardshrink(self, lambd)
}

#' @export
torch_selu <- function(self) {
    C_torch_selu(self)
}

#' @export
torch_celu <- function(self, alpha = 1.0) {
    C_torch_celu(self, alpha)
}

#' @export
torch_silu <- function(self) {
    C_torch_silu(self)
}

#' @export
torch_mish <- function(self) {
    C_torch_mish(self)
}

#' @export
torch_sinc <- function(self) {
    C_torch_sinc(self)
}

#' @export
torch_sinh <- function(self) {
    C_torch_sinh(self)
}

#' @export
torch_square <- function(self) {
    C_torch_square(self)
}

#' @export
torch_tan <- function(self) {
    C_torch_tan(self)
}

#' @export
torch_fliplr <- function(self) {
    C_torch_fliplr(self)
}

#' @export
torch_flipud <- function(self) {
    C_torch_flipud(self)
}

#' @export
torch_fix <- function(self) {
    C_torch_fix(self)
}

#' @export
torch_var <- function(self, unbiased = TRUE) {
    C_torch_var(self, as.logical(unbiased))
}

#' @export
torch_positive <- function(self) {
    C_torch_positive(self)
}

#' @export
torch_subtract <- function(self, other, alpha = 1) {
    C_torch_subtract(self, other, alpha)
}

#' @export
torch_rsub <- function(self, other, alpha = 1) {
    C_torch_rsub(self, other, alpha)
}

#' @export
torch_bitwise_and <- function(self, other) {
    C_torch_bitwise_and(self, other)
}

#' @export
torch_bitwise_or <- function(self, other) {
    C_torch_bitwise_or(self, other)
}

#' @export
torch_bitwise_xor <- function(self, other) {
    C_torch_bitwise_xor(self, other)
}

#' @export
torch_bitwise_left_shift <- function(self, other) {
    C_torch_bitwise_left_shift(self, other)
}

#' @export
torch_bitwise_right_shift <- function(self, other) {
    C_torch_bitwise_right_shift(self, other)
}

#' @export
torch_diag <- function(self, diagonal = 0) {
    C_torch_diag(self, as.integer(diagonal))
}

#' @export
torch_tril <- function(self, diagonal = 0) {
    C_torch_tril(self, as.integer(diagonal))
}

#' @export
torch_trace <- function(self) {
    C_torch_trace(self)
}

#' @export
torch_not_equal <- function(self, other) {
    C_torch_not_equal(self, other)
}

#' @export
torch_greater_equal <- function(self, other) {
    C_torch_greater_equal(self, other)
}

#' @export
torch_less_equal <- function(self, other) {
    C_torch_less_equal(self, other)
}

#' @export
torch_greater <- function(self, other) {
    C_torch_greater(self, other)
}

#' @export
torch_less <- function(self, other) {
    C_torch_less(self, other)
}

#' @export
torch_take <- function(self, index) {
    C_torch_take(self, index)
}

#' @export
torch_masked_select <- function(self, mask) {
    C_torch_masked_select(self, mask)
}

#' @export
torch_nonzero <- function(self) {
    C_torch_nonzero(self)
}

#' @export
torch_argwhere <- function(self) {
    C_torch_argwhere(self)
}

#' @export
torch_swapaxes <- function(self, axis0, axis1) {
    C_torch_swapaxes(self, as.integer(axis0), as.integer(axis1))
}

#' @export
torch_swapdims <- function(self, dim0, dim1) {
    C_torch_swapdims(self, as.integer(dim0), as.integer(dim1))
}

#' @export
torch_cholesky <- function(self, upper = FALSE) {
    C_torch_cholesky(self, as.logical(upper))
}

#' @export
torch_cholesky_inverse <- function(self, upper = FALSE) {
    C_torch_cholesky_inverse(self, as.logical(upper))
}

#' @export
torch_orgqr <- function(self, input2) {
    C_torch_orgqr(self, input2)
}

#' @export
torch_lgamma <- function(self) {
    C_torch_lgamma(self)
}

#' @export
torch_digamma <- function(self) {
    C_torch_digamma(self)
}

#' @export
torch_erfinv <- function(self) {
    C_torch_erfinv(self)
}

#' @export
torch_i0 <- function(self) {
    C_torch_i0(self)
}

#' @export
torch_signbit <- function(self) {
    C_torch_signbit(self)
}

#' @export
torch_dist <- function(self, other, p = 2) {
    C_torch_dist(self, other, p)
}

#' @export
torch_atan2 <- function(self, other) {
    C_torch_atan2(self, other)
}

#' @export
torch_arctan2 <- function(self, other) {
    C_torch_arctan2(self, other)
}

#' @export
torch_lerp <- function(self, end, weight) {
    C_torch_lerp(self, end, weight)
}

#' @export
torch_fmod <- function(self, other) {
    C_torch_fmod(self, other)
}

#' @export
torch_hypot <- function(self, other) {
    C_torch_hypot(self, other)
}

#' @export
torch_igamma <- function(self, other) {
    C_torch_igamma(self, other)
}

#' @export
torch_igammac <- function(self, other) {
    C_torch_igammac(self, other)
}

#' @export
torch_nextafter <- function(self, other) {
    C_torch_nextafter(self, other)
}

#' @export
torch_fmin <- function(self, other) {
    C_torch_fmin(self, other)
}

#' @export
torch_fmax <- function(self, other) {
    C_torch_fmax(self, other)
}

#' @export
torch_minimum <- function(self, other) {
    C_torch_minimum(self, other)
}

#' @export
torch_msort <- function(self) {
    C_torch_msort(self)
}

#' @export
torch_argsort <- function(self, dim = -1, descending = FALSE) {
    C_torch_argsort(self, as.integer(dim), as.logical(descending))
}

#' @export
torch_float_power <- function(self, exponent) {
    C_torch_float_power(self, exponent)
}

#' @export
torch_alias <- function(self) {
    C_torch_alias(self)
}

#' @export
torch_glu <- function(self, dim = -1) {
    C_torch_glu(self, as.integer(dim))
}

#' @export
torch_hardsigmoid <- function(self) {
    C_torch_hardsigmoid(self)
}

#' @export
torch_hardswish <- function(self) {
    C_torch_hardswish(self)
}

#' @export
torch_leaky_relu <- function(self, negative_slope = 0.01) {
    C_torch_leaky_relu(self, negative_slope)
}

#' @export
torch_log_sigmoid <- function(self) {
    C_torch_log_sigmoid(self)
}

#' @export
torch_softshrink <- function(self, lambd = 0.5) {
    C_torch_softshrink(self, lambd)
}

#' @export
torch_isfinite <- function(self) {
    C_torch_isfinite(self)
}

#' @export
torch_isinf <- function(self) {
    C_torch_isinf(self)
}

#' @export
torch_isposinf <- function(self) {
    C_torch_isposinf(self)
}

#' @export
torch_isneginf <- function(self) {
    C_torch_isneginf(self)
}

#' @export
torch_special_entr <- function(self) {
    C_torch_special_entr(self)
}

#' @export
torch_special_ndtri <- function(self) {
    C_torch_special_ndtri(self)
}

#' @export
torch_special_log_ndtr <- function(self) {
    C_torch_special_log_ndtr(self)
}

#' @export
torch_special_expm1 <- function(self) {
    C_torch_special_expm1(self)
}

#' @export
torch_special_exp2 <- function(self) {
    C_torch_special_exp2(self)
}

#' @export
torch_special_psi <- function(self) {
    C_torch_special_psi(self)
}

#' @export
torch_special_digamma <- function(self) {
    C_torch_special_digamma(self)
}

#' @export
torch_special_gammaln <- function(self) {
    C_torch_special_gammaln(self)
}

#' @export
torch_special_erf <- function(self) {
    C_torch_special_erf(self)
}

#' @export
torch_special_erfc <- function(self) {
    C_torch_special_erfc(self)
}

#' @export
torch_special_erfcx <- function(self) {
    C_torch_special_erfcx(self)
}

#' @export
torch_special_erfinv <- function(self) {
    C_torch_special_erfinv(self)
}

#' @export
torch_special_ndtr <- function(self) {
    C_torch_special_ndtr(self)
}

#' @export
torch_special_xlog1py <- function(self, other) {
    C_torch_special_xlog1py(self, other)
}

#' @export
torch_special_xlogy <- function(self, other) {
    C_torch_special_xlogy(self, other)
}

#' @export
torch_special_zeta <- function(self, other) {
    C_torch_special_zeta(self, other)
}

#' @export
torch_special_i0 <- function(self) {
    C_torch_special_i0(self)
}

#' @export
torch_special_i0e <- function(self) {
    C_torch_special_i0e(self)
}

#' @export
torch_special_i1 <- function(self) {
    C_torch_special_i1(self)
}

#' @export
torch_special_i1e <- function(self) {
    C_torch_special_i1e(self)
}

#' @export
torch_special_expit <- function(self) {
    C_torch_special_expit(self)
}

#' @export
torch_special_sinc <- function(self) {
    C_torch_special_sinc(self)
}

#' @export
torch_special_round <- function(self, decimals = 0) {
    C_torch_special_round(self, as.integer(decimals))
}

#' @export
torch_special_log1p <- function(self) {
    C_torch_special_log1p(self)
}

#' @export
torch_special_gammainc <- function(self, other) {
    C_torch_special_gammainc(self, other)
}

#' @export
torch_special_gammaincc <- function(self, other) {
    C_torch_special_gammaincc(self, other)
}

#' @export
torch_special_multigammaln <- function(self, p) {
    C_torch_special_multigammaln(self, as.integer(p))
}

#' @export
torch_linalg_cholesky <- function(self, upper = FALSE) {
    C_torch_linalg_cholesky(self, as.logical(upper))
}

#' @export
torch_linalg_det <- function(A) {
    C_torch_linalg_det(A)
}

#' @export
torch_det <- function(self) {
    C_torch_det(self)
}

#' @export
torch_linalg_matmul <- function(self, other) {
    C_torch_linalg_matmul(self, other)
}

#' @export
torch_linalg_matrix_exp <- function(self) {
    C_torch_linalg_matrix_exp(self)
}

#' @export
torch_logdet <- function(self) {
    C_torch_logdet(self)
}

#' @export
torch_linalg_eigvals <- function(self) {
    C_torch_linalg_eigvals(self)
}

#' @export
torch_linalg_householder_product <- function(input, tau) {
    C_torch_linalg_householder_product(input, tau)
}

#' @export
torch_linalg_inv <- function(A) {
    C_torch_linalg_inv(A)
}

#' @export
torch_inverse <- function(self) {
    C_torch_inverse(self)
}

#' @export
torch_inner <- function(self, other) {
    C_torch_inner(self, other)
}

#' @export
torch_ger <- function(self, vec2) {
    C_torch_ger(self, vec2)
}

#' @export
torch_linalg_tensorinv <- function(self, ind = 2) {
    C_torch_linalg_tensorinv(self, as.integer(ind))
}

#' @export
torch_linalg_matrix_power <- function(self, n) {
    C_torch_linalg_matrix_power(self, as.integer(n))
}

#' @export
torch_special_airy_ai <- function(x) {
    C_torch_special_airy_ai(x)
}

#' @export
torch_special_bessel_j0 <- function(self) {
    C_torch_special_bessel_j0(self)
}

#' @export
torch_special_bessel_j1 <- function(self) {
    C_torch_special_bessel_j1(self)
}

#' @export
torch_special_bessel_y0 <- function(self) {
    C_torch_special_bessel_y0(self)
}

#' @export
torch_special_bessel_y1 <- function(self) {
    C_torch_special_bessel_y1(self)
}

#' @export
torch_special_chebyshev_polynomial_t <- function(x, n) {
    C_torch_special_chebyshev_polynomial_t(x, n)
}

#' @export
torch_special_chebyshev_polynomial_u <- function(x, n) {
    C_torch_special_chebyshev_polynomial_u(x, n)
}

#' @export
torch_special_chebyshev_polynomial_v <- function(x, n) {
    C_torch_special_chebyshev_polynomial_v(x, n)
}

#' @export
torch_special_chebyshev_polynomial_w <- function(x, n) {
    C_torch_special_chebyshev_polynomial_w(x, n)
}

#' @export
torch_special_hermite_polynomial_h <- function(x, n) {
    C_torch_special_hermite_polynomial_h(x, n)
}

#' @export
torch_special_hermite_polynomial_he <- function(x, n) {
    C_torch_special_hermite_polynomial_he(x, n)
}

#' @export
torch_special_laguerre_polynomial_l <- function(x, n) {
    C_torch_special_laguerre_polynomial_l(x, n)
}

#' @export
torch_special_legendre_polynomial_p <- function(x, n) {
    C_torch_special_legendre_polynomial_p(x, n)
}

#' @export
torch_special_modified_bessel_i0 <- function(self) {
    C_torch_special_modified_bessel_i0(self)
}

#' @export
torch_special_modified_bessel_i1 <- function(self) {
    C_torch_special_modified_bessel_i1(self)
}

#' @export
torch_special_modified_bessel_k0 <- function(self) {
    C_torch_special_modified_bessel_k0(self)
}

#' @export
torch_special_modified_bessel_k1 <- function(self) {
    C_torch_special_modified_bessel_k1(self)
}

#' @export
torch_special_scaled_modified_bessel_k0 <- function(x) {
    C_torch_special_scaled_modified_bessel_k0(x)
}

#' @export
torch_special_scaled_modified_bessel_k1 <- function(x) {
    C_torch_special_scaled_modified_bessel_k1(x)
}

#' @export
torch_special_shifted_chebyshev_polynomial_t <- function(x, n) {
    C_torch_special_shifted_chebyshev_polynomial_t(x, n)
}

#' @export
torch_special_shifted_chebyshev_polynomial_u <- function(x, n) {
    C_torch_special_shifted_chebyshev_polynomial_u(x, n)
}

#' @export
torch_special_shifted_chebyshev_polynomial_v <- function(x, n) {
    C_torch_special_shifted_chebyshev_polynomial_v(x, n)
}

#' @export
torch_special_shifted_chebyshev_polynomial_w <- function(x, n) {
    C_torch_special_shifted_chebyshev_polynomial_w(x, n)
}

#' @export
torch_special_spherical_bessel_j0 <- function(x) {
    C_torch_special_spherical_bessel_j0(x)
}


# ---- Method table entries ----


.tensor_methods$absolute <- function(self) C_torch_absolute(self)

.tensor_methods$angle <- function(self) C_torch_angle(self)

.tensor_methods$sgn <- function(self) C_torch_sgn(self)

.tensor_methods$acos <- function(self) C_torch_acos(self)

.tensor_methods$arccos <- function(self) C_torch_arccos(self)

.tensor_methods$all <- function(self, dim, keepdim = FALSE) {
    C_torch_all(self, as.integer(dim), as.logical(keepdim))
}

.tensor_methods$any <- function(self, dim, keepdim = FALSE) {
    C_torch_any(self, as.integer(dim), as.logical(keepdim))
}

.tensor_methods$acosh <- function(self) C_torch_acosh(self)

.tensor_methods$arccosh <- function(self) C_torch_arccosh(self)

.tensor_methods$asinh <- function(self) C_torch_asinh(self)

.tensor_methods$arcsinh <- function(self) C_torch_arcsinh(self)

.tensor_methods$atanh <- function(self) C_torch_atanh(self)

.tensor_methods$arctanh <- function(self) C_torch_arctanh(self)

.tensor_methods$asin <- function(self) C_torch_asin(self)

.tensor_methods$arcsin <- function(self) C_torch_arcsin(self)

.tensor_methods$atan <- function(self) C_torch_atan(self)

.tensor_methods$arctan <- function(self) C_torch_arctan(self)

.tensor_methods$bitwise_not <- function(self) C_torch_bitwise_not(self)

.tensor_methods$copysign <- function(self, other) {
    C_torch_copysign(self, other)
}

.tensor_methods$logical_xor <- function(self, other) {
    C_torch_logical_xor(self, other)
}

.tensor_methods$logical_and <- function(self, other) {
    C_torch_logical_and(self, other)
}

.tensor_methods$logical_or <- function(self, other) {
    C_torch_logical_or(self, other)
}

.tensor_methods$clamp_max <- function(self, max) {
    C_torch_clamp_max(self, max)
}

.tensor_methods$clamp_min <- function(self, min) {
    C_torch_clamp_min(self, min)
}

.tensor_methods$cosh <- function(self) C_torch_cosh(self)

.tensor_methods$corrcoef <- function(self) C_torch_corrcoef(self)

.tensor_methods$diag_embed <- function(self, offset = 0, dim1 = -2, dim2 = -1) {
    C_torch_diag_embed(self, as.integer(offset), as.integer(dim1), as.integer(dim2))
}

.tensor_methods$diagflat <- function(self, offset = 0) {
    C_torch_diagflat(self, as.integer(offset))
}

.tensor_methods$diagonal <- function(self, offset = 0, dim1 = 0, dim2 = 1) {
    C_torch_diagonal(self, as.integer(offset), as.integer(dim1), as.integer(dim2))
}

.tensor_methods$divide <- function(self, other) {
    C_torch_divide(self, other)
}

.tensor_methods$true_divide <- function(self, other) {
    C_torch_true_divide(self, other)
}

.tensor_methods$dot <- function(self, tensor) {
    C_torch_dot(self, tensor)
}

.tensor_methods$vdot <- function(self, other) {
    C_torch_vdot(self, other)
}

.tensor_methods$erf <- function(self) C_torch_erf(self)

.tensor_methods$erfc <- function(self) C_torch_erfc(self)

.tensor_methods$exp2 <- function(self) C_torch_exp2(self)

.tensor_methods$expm1 <- function(self) C_torch_expm1(self)

.tensor_methods$frac <- function(self) C_torch_frac(self)

.tensor_methods$gcd <- function(self, other) {
    C_torch_gcd(self, other)
}

.tensor_methods$lcm <- function(self, other) {
    C_torch_lcm(self, other)
}

.tensor_methods$isnan <- function(self) C_torch_isnan(self)

.tensor_methods$isreal <- function(self) C_torch_isreal(self)

.tensor_methods$kron <- function(self, other) {
    C_torch_kron(self, other)
}

.tensor_methods$log1p <- function(self) C_torch_log1p(self)

.tensor_methods$logaddexp <- function(self, other) {
    C_torch_logaddexp(self, other)
}

.tensor_methods$logaddexp2 <- function(self, other) {
    C_torch_logaddexp2(self, other)
}

.tensor_methods$xlogy <- function(self, other) {
    C_torch_xlogy(self, other)
}

.tensor_methods$logcumsumexp <- function(self, dim) {
    C_torch_logcumsumexp(self, as.integer(dim))
}

.tensor_methods$matrix_power <- function(self, n) {
    C_torch_matrix_power(self, as.integer(n))
}

.tensor_methods$matrix_exp <- function(self) C_torch_matrix_exp(self)

.tensor_methods$median <- function(self) C_torch_median(self)

.tensor_methods$nanmedian <- function(self) C_torch_nanmedian(self)

.tensor_methods$multiply <- function(self, other) {
    C_torch_multiply(self, other)
}

.tensor_methods$mv <- function(self, vec) {
    C_torch_mv(self, vec)
}

.tensor_methods$mvlgamma <- function(self, p) {
    C_torch_mvlgamma(self, as.integer(p))
}

.tensor_methods$movedim <- function(self, source, destination) {
    C_torch_movedim(self, as.integer(source), as.integer(destination))
}

.tensor_methods$moveaxis <- function(self, source, destination) {
    C_torch_moveaxis(self, as.integer(source), as.integer(destination))
}

.tensor_methods$adjoint <- function(self) C_torch_adjoint(self)

.tensor_methods$pinverse <- function(self, rcond = 1e-15) {
    C_torch_pinverse(self, as.double(rcond))
}

.tensor_methods$rad2deg <- function(self) C_torch_rad2deg(self)

.tensor_methods$deg2rad <- function(self) C_torch_deg2rad(self)

.tensor_methods$ravel <- function(self) C_torch_ravel(self)

.tensor_methods$reciprocal <- function(self) C_torch_reciprocal(self)

.tensor_methods$negative <- function(self) C_torch_negative(self)

.tensor_methods$prelu <- function(self, weight) {
    C_torch_prelu(self, weight)
}

.tensor_methods$hardshrink <- function(self, lambd = 0.5) {
    C_torch_hardshrink(self, lambd)
}

.tensor_methods$sinc <- function(self) C_torch_sinc(self)

.tensor_methods$sinh <- function(self) C_torch_sinh(self)

.tensor_methods$square <- function(self) C_torch_square(self)

.tensor_methods$tan <- function(self) C_torch_tan(self)

.tensor_methods$fliplr <- function(self) C_torch_fliplr(self)

.tensor_methods$flipud <- function(self) C_torch_flipud(self)

.tensor_methods$fix <- function(self) C_torch_fix(self)

.tensor_methods$var <- function(self, unbiased = TRUE) {
    C_torch_var(self, as.logical(unbiased))
}

.tensor_methods$positive <- function(self) C_torch_positive(self)

.tensor_methods$subtract <- function(self, other, alpha = 1) {
    C_torch_subtract(self, other, alpha)
}

.tensor_methods$bitwise_and <- function(self, other) {
    C_torch_bitwise_and(self, other)
}

.tensor_methods$bitwise_or <- function(self, other) {
    C_torch_bitwise_or(self, other)
}

.tensor_methods$bitwise_xor <- function(self, other) {
    C_torch_bitwise_xor(self, other)
}

.tensor_methods$bitwise_left_shift <- function(self, other) {
    C_torch_bitwise_left_shift(self, other)
}

.tensor_methods$bitwise_right_shift <- function(self, other) {
    C_torch_bitwise_right_shift(self, other)
}

.tensor_methods$diag <- function(self, diagonal = 0) {
    C_torch_diag(self, as.integer(diagonal))
}

.tensor_methods$tril <- function(self, diagonal = 0) {
    C_torch_tril(self, as.integer(diagonal))
}

.tensor_methods$trace <- function(self) C_torch_trace(self)

.tensor_methods$not_equal <- function(self, other) {
    C_torch_not_equal(self, other)
}

.tensor_methods$greater_equal <- function(self, other) {
    C_torch_greater_equal(self, other)
}

.tensor_methods$less_equal <- function(self, other) {
    C_torch_less_equal(self, other)
}

.tensor_methods$greater <- function(self, other) {
    C_torch_greater(self, other)
}

.tensor_methods$less <- function(self, other) {
    C_torch_less(self, other)
}

.tensor_methods$take <- function(self, index) {
    C_torch_take(self, index)
}

.tensor_methods$masked_select <- function(self, mask) {
    C_torch_masked_select(self, mask)
}

.tensor_methods$nonzero <- function(self) C_torch_nonzero(self)

.tensor_methods$argwhere <- function(self) C_torch_argwhere(self)

.tensor_methods$swapaxes <- function(self, axis0, axis1) {
    C_torch_swapaxes(self, as.integer(axis0), as.integer(axis1))
}

.tensor_methods$swapdims <- function(self, dim0, dim1) {
    C_torch_swapdims(self, as.integer(dim0), as.integer(dim1))
}

.tensor_methods$cholesky <- function(self, upper = FALSE) {
    C_torch_cholesky(self, as.logical(upper))
}

.tensor_methods$cholesky_inverse <- function(self, upper = FALSE) {
    C_torch_cholesky_inverse(self, as.logical(upper))
}

.tensor_methods$orgqr <- function(self, input2) {
    C_torch_orgqr(self, input2)
}

.tensor_methods$lgamma <- function(self) C_torch_lgamma(self)

.tensor_methods$digamma <- function(self) C_torch_digamma(self)

.tensor_methods$erfinv <- function(self) C_torch_erfinv(self)

.tensor_methods$i0 <- function(self) C_torch_i0(self)

.tensor_methods$signbit <- function(self) C_torch_signbit(self)

.tensor_methods$dist <- function(self, other, p = 2) {
    C_torch_dist(self, other, p)
}

.tensor_methods$atan2 <- function(self, other) {
    C_torch_atan2(self, other)
}

.tensor_methods$arctan2 <- function(self, other) {
    C_torch_arctan2(self, other)
}

.tensor_methods$lerp <- function(self, end, weight) {
    C_torch_lerp(self, end, weight)
}

.tensor_methods$fmod <- function(self, other) {
    C_torch_fmod(self, other)
}

.tensor_methods$hypot <- function(self, other) {
    C_torch_hypot(self, other)
}

.tensor_methods$igamma <- function(self, other) {
    C_torch_igamma(self, other)
}

.tensor_methods$igammac <- function(self, other) {
    C_torch_igammac(self, other)
}

.tensor_methods$nextafter <- function(self, other) {
    C_torch_nextafter(self, other)
}

.tensor_methods$fmin <- function(self, other) {
    C_torch_fmin(self, other)
}

.tensor_methods$fmax <- function(self, other) {
    C_torch_fmax(self, other)
}

.tensor_methods$minimum <- function(self, other) {
    C_torch_minimum(self, other)
}

.tensor_methods$msort <- function(self) C_torch_msort(self)

.tensor_methods$argsort <- function(self, dim = -1, descending = FALSE) {
    C_torch_argsort(self, as.integer(dim), as.logical(descending))
}

.tensor_methods$float_power <- function(self, exponent) {
    C_torch_float_power(self, exponent)
}

.tensor_methods$alias <- function(self) C_torch_alias(self)

.tensor_methods$isfinite <- function(self) C_torch_isfinite(self)

.tensor_methods$isinf <- function(self) C_torch_isinf(self)

.tensor_methods$isposinf <- function(self) C_torch_isposinf(self)

.tensor_methods$isneginf <- function(self) C_torch_isneginf(self)

.tensor_methods$det <- function(self) C_torch_det(self)

.tensor_methods$logdet <- function(self) C_torch_logdet(self)

.tensor_methods$inverse <- function(self) C_torch_inverse(self)

.tensor_methods$inner <- function(self, other) {
    C_torch_inner(self, other)
}

.tensor_methods$ger <- function(self, vec2) {
    C_torch_ger(self, vec2)
}
